{
  "hash": "058f16ee9c3f1b28271ae8d52808b552",
  "result": {
    "engine": "jupyter",
    "markdown": "\n\n# The Seven Scenarios {#sec-scenarios}\n\n::: {.chapter-opening}\nFrom continued diesel dependence to near-complete decarbonisation in thirty years. Each scenario below represents a plausible combination of technologies, policies, and institutional arrangements. They are structured counterfactuals, not forecasts.\n:::\n\n## Scenario Overview\n\nThe seven scenarios capture the principal strategic choices available to the Maldives, differing along four dimensions: technology mix (diesel, solar, wind, battery, LNG, submarine cable), geographic scope (island-by-island versus interconnected), international dependence (domestic-only versus reliance on India), and implementation timeline (immediate versus phased).\n\n::: {#tbl-scenario-overview .cell tbl-cap='Summary of seven scenarios: technology mix, geographic scope, and key differentiators.' execution_count=2}\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=2}\n| Scenario              | Technology                                             | Geographic Focus                                | Key Feature                                           | India Cable   |\n|:----------------------|:-------------------------------------------------------|:------------------------------------------------|:------------------------------------------------------|:--------------|\n| S1 — BAU (Diesel)     | Diesel generators only                                 | All islands (status quo)                        | No new RE investment; continued diesel expansion      | No            |\n| S2 — Full Integration | India HVDC cable + solar + battery                     | Greater Malé via cable; outer islands via solar | 700 km submarine cable to India; imports at $0.06/kWh | Yes           |\n| S3 — National Grid    | Solar + battery + inter-island cables                  | All islands; limited interconnection            | Domestic RE only; no international cable              | No            |\n| S4 — Islanded Green   | Solar + battery (island-by-island)                     | Each island independently                       | Modular deployment; no grid extension                 | No            |\n| S5 — Near-Shore Solar | Solar farms on uninhabited islands + battery           | Greater Malé + outer islands                    | 104 MW on uninhabited islands near Malé               | No            |\n| S6 — Maximum RE       | Floating solar + near-shore + rooftop + wind + battery | All islands; floating solar on lagoons          | 195 MW floating + 80 MW wind (GoM Roadmap)            | No            |\n| S7 — LNG Transition   | LNG terminal + solar + battery                         | Greater Malé via LNG; outer islands via solar   | 140 MW Gulhifalhu LNG terminal from 2031              | No            |\n:::\n:::\n\n\nOnly S2 involves an international submarine cable. S3, S4, and S5 rely entirely on domestic renewables. S6 adds floating solar and wind. S7 introduces LNG as a bridge fuel for Greater Malé.\n\n## S1 — BAU: Continued Diesel {#sec-s1}\n\nThe business-as-usual scenario is the analytical counterfactual: the Maldives continues expanding diesel generation in step with demand, making no new renewable investments beyond the existing pipeline. The Government's Energy Roadmap [-@gom_roadmap2024] envisions otherwise, but BAU defines the costs that would accumulate absent policy action. Its purpose is not to predict, but to establish the baseline against which all alternatives are measured.\n\n::: {.callout-warning}\nBAU is not a realistic future — it represents *what happens if no policy action is taken*. It exists as the analytical baseline against which all alternatives are measured.\n:::\n\nThe BAU scenario assumes electricity demand grows at 5 per cent per year^[@irena_roadmap_maldives2015; STELCO Annual Reports confirm CAGR of approximately 5%.]. Diesel fuel is projected to cost $0\\.85 per litre in 2026, escalating at 2 per cent per year in real terms^[See [Appendix B](B-parameters.qmd) for fuel price source and sensitivity range.]. No new solar or battery capacity is deployed, and all externalities accumulate at full diesel intensity throughout.\n\n## S2 — Full Integration: The India Cable {#sec-s2}\n\n\n\nThe Full Integration scenario centres on a 700-kilometre HVDC submarine cable connecting the Maldives to India's national grid^[@osowog2023; cable route distance estimated from Kanyakumari, India to Malé.]. Imported electricity would reach Greater Malé at an estimated $0\\.06/kWh^[@iea_india2023; Indian wholesale price plus cross-border transmission premium.]. Outer islands, too distant from the cable route, would still receive solar-plus-battery systems.\n\nAdditional CAPEX: approximately $3\\.1 billion relative to BAU (cable, converters, landing stations, grid upgrades). NPV savings: $10\\.3 billion. Even with the largest upfront cost of any scenario, the cable pathway is superior to continued diesel.\n\nThe cable provides stable baseload power to Greater Malé (57 per cent of national demand), where extreme urban density limits rooftop solar. The Indian grid's emission factor of 0\\.70 kgCO₂/kWh^[@iea_india2023.] is lower than diesel and declining at approximately 2 per cent per year. The cable also eliminates direct fuel import dependency, replacing it with electricity import dependency.\n\nThe risks are substantial. Outage rates for comparable submarine cables (NorNed, Basslink^[NorNed: 580 km North Sea cable, operational since 2008; Basslink: 290 km Bass Strait cable, operational since 2006. Combined record yields λ ≈ 0.15 faults per year.]) average 0.15 per year, with repair times of one to six months. The Maldives would need to maintain backup diesel capacity, partially undermining fuel savings. Geopolitically, dependence on a single foreign electricity supplier for over half of supply carries diplomatic leverage implications. No cost-sharing agreement exists; the base case assumes the Maldives bears 100 per cent of cable cost, though sensitivity analysis explores 50 per cent cost-sharing.\n\n## S3 — National Grid: Domestic RE with Interconnection {#sec-s3}\n\n\n\nFull domestic energy independence. Solar-plus-battery on every island, complemented by 14 km of inter-island cables linking the three islands nearest to Malé. No international cable, no LNG, no external dependence. Greater Malé is constrained to ~34 MWp of rooftop solar (@znes_flensburg).\n\nAdditional CAPEX: ~$1\\.0 billion. NPV savings: $11\\.3 billion. The least-cost engine optimises technology assignment island-by-island, factoring in solar resources, land, demand, and cable economics.\n\nStrength: the Maldives controls its entire supply chain. No geopolitical cable risk, no fuel price volatility. Modular deployment means early islands generate savings that finance later phases.\n\n## S4 — Islanded Green: Solar+Battery on Every Island {#sec-s4}\n\n\n\nThe most implementable pathway. Each island gets its own solar-plus-battery system, sized to local demand and land availability. No cables, no cross-island coordination, no international dependencies.\n\nCAPEX: ~$1\\.4 billion. NPV savings: $10\\.3 billion. MCA implementation feasibility score: 0.80 (highest among all alternatives), reflecting proven technology and no regulatory or diplomatic prerequisites. Geographic equity is maximal: no community waits on diesel while others receive renewables. The trade-off is forgone scale economies from interconnection, plus island logistics that add a ~30% cost premium^[@irena_sids2023; @atlantic_council2024.]. Greater Malé achieves only ~18 MWp, leaving it with the highest residual diesel share among RE scenarios.\n\n## S5 — Near-Shore Solar: Uninhabited Island Solar Farms {#sec-s5}\n\n\n\nMalé has almost no land for solar — one of the densest urban footprints in the world. Near-Shore Solar solves this by deploying 104 MW on uninhabited islands within 10 km: Thilafushi (industrial), Gulhifalhu (port development), Funadhoo, and Dhoonidhoo. Short submarine cables link these farms to Greater Malé.\n\nCAPEX: ~$1\\.2 billion. NPV savings: $12\\.0 billion. Greater Malé’s RE share jumps from ~4% (rooftop only) to ~25%, with no international infrastructure or geopolitical exposure. Outer islands receive standard solar-battery as in other scenarios. Implementation challenges include environmental permitting (Funadhoo and Dhoonidhoo may have ecological sensitivities), land tenure on industrial sites, and engineering shallow-reef submarine cables.\n\n## S6 — Maximum RE: Floating Solar and Beyond {#sec-s6}\n\n\n\nThe most ambitious domestic pathway, deploying every identified RE source: rooftop solar on all islands (34 MWp on Greater Malé), ground-mount where land permits, 104 MW near-shore, 195 MW floating solar (100 MW Malé lagoon + 95 MW outer atolls), and 80 MW wind^[@gom_roadmap2024 §4.7.2: \"80 MW wind potential.\"]. Solar peaks at midday; wind adds generation in the evening and under overcast conditions. The floating solar target aligns with the @gom_roadmap2024.\n\nCAPEX: ~$1\\.8 billion. NPV savings: $13\\.8 billion. Final RE share reaches 64% — one of the highest achievable by any SIDS. Diesel dependence and foreign energy exposure are both minimised.\n\nWind at 80 MW contributes ~175 GWh/year (25% CF, below global averages due to the equatorial location). Its RE share is modest (~4–5 percentage points) but it provides generation diversity at hours when solar output is low.\n\nFloating solar carries a ~50% cost premium for marine installation, anchoring, and corrosion resistance. The technology is commercial but largely untested at scale in tropical oceans. If floating solar underperforms, the remaining near-shore, rooftop, and wind capacity still delivers strong returns. The scenario therefore contains a built-in fallback.\n\n## S7 — LNG Transition: Gas for Malé, Solar for Islands {#sec-s7}\n\n\n\nThe pragmatic bridge. A 140 MW LNG terminal at Gulhifalhu (operational 2031) replaces diesel in Greater Malé. Emission factor: 0\\.40 kgCO₂/kWh^[@ipcc2006.] — 44% lower than diesel. Outer islands follow standard solar-battery.\n\nCAPEX: ~$1\\.4 billion. NPV savings: $13\\.3 billion. Fastest payback (6 years). Highest IRR (44\\.2%). The economics are strong: modest capital, immediate fuel savings, flexible dispatchable baseload that complements solar.\n\nThe catch: lock-in. A 140 MW terminal means 30-year gas contracts, maintenance obligations, and institutional inertia. The Maldives would replace diesel dependence with LNG dependence. LNG is cleaner (44% lower emissions) and cheaper, but it does not achieve the deep decarbonisation of the renewable pathways, and LNG prices are themselves volatile (cf. the 2022 European price crisis). This scenario is viable only if paired with binding RE ramp commitments that prevent LNG from displacing renewables rather than bridging to them.\n\n## Scenario Comparison Matrix\n\nThe bubble chart below provides a visual synthesis of how the seven scenarios compare along two of the most important dimensions: cumulative emissions (horizontal axis, with lower emissions to the right) and NPV savings relative to diesel BAU (vertical axis, with higher savings toward the top). The size of each bubble is proportional to the total capital expenditure required, allowing the reader to see at a glance which pathways achieve the largest economic and environmental benefits and at what investment cost.\n\n::: {.cell execution_count=9}\n\n::: {.cell-output .cell-output-display}\n![Scenario positioning on cost vs. emissions dimensions. Bubble size represents total CAPEX.](03-scenarios_files/figure-docx/fig-scenario-matrix-output-1.png){#fig-scenario-matrix}\n:::\n:::\n\n\nHigher savings and lower emissions tend to go together, indicating limited tension between economic efficiency and environmental performance. The India cable (S2) requires the largest investment without delivering the largest returns. S6 pushes toward the frontier on both dimensions, while S7 occupies an intermediate emissions position.\n\n",
    "supporting": [
      "03-scenarios_files\\figure-docx"
    ],
    "filters": []
  }
}