{
  "hash": "b14c4d296d5bdd567d2e1f8077862188",
  "result": {
    "engine": "jupyter",
    "markdown": "---\n---\n\n\n\n# The Seven Scenarios {#sec-scenarios}\n\n::: {.chapter-opening}\nThis chapter describes each of the seven electricity transition pathways evaluated in this analysis. These scenarios are not forecasts or predictions of what will happen, but structured *what-if* analyses, each representing a coherent combination of technologies, policies, and institutional arrangements that the Maldives could plausibly pursue over the next three decades. Together, they span the full range of realistic options — from continued diesel dependence to ambitious renewable energy transformation — enabling a systematic comparison of costs, benefits, and trade-offs.\n:::\n\n## Scenario Overview\n\nThe seven scenarios are designed to capture the principal strategic choices available to the Maldives. They differ along four main dimensions: the technology mix (diesel, solar, battery, LNG, submarine cable), the geographic scope (island-by-island versus interconnected systems), the degree of international dependence (domestic-only versus reliance on India), and the implementation timeline (immediate versus phased). The table below summarises these key characteristics before each scenario is described in detail.\n\n::: {#tbl-scenario-overview .cell tbl-cap='Summary of seven scenarios: technology mix, geographic scope, and key differentiators.' execution_count=2}\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=2}\n| Scenario              | Technology                                      | Geographic Focus                                | Key Feature                                           | India Cable   |\n|:----------------------|:------------------------------------------------|:------------------------------------------------|:------------------------------------------------------|:--------------|\n| S1 — BAU (Diesel)     | Diesel generators only                          | All islands (status quo)                        | No new RE investment; continued diesel expansion      | No            |\n| S2 — Full Integration | India HVDC cable + solar + battery              | Greater Malé via cable; outer islands via solar | 700 km submarine cable to India; imports at $0.06/kWh | Yes           |\n| S3 — National Grid    | Solar + battery + inter-island cables           | All islands; limited interconnection            | Domestic RE only; no international cable              | No            |\n| S4 — Islanded Green   | Solar + battery (island-by-island)              | Each island independently                       | Modular deployment; no grid extension                 | No            |\n| S5 — Near-Shore Solar | Solar farms on uninhabited islands + battery    | Greater Malé + outer islands                    | 104 MW on uninhabited islands near Malé               | No            |\n| S6 — Maximum RE       | Floating solar + near-shore + rooftop + battery | All islands; floating solar on lagoons          | 195 MW floating solar (GoM Roadmap target)            | No            |\n| S7 — LNG Transition   | LNG terminal + solar + battery                  | Greater Malé via LNG; outer islands via solar   | 140 MW Gulhifalhu LNG terminal from 2031              | No            |\n:::\n:::\n\n\nThe overview table reveals important structural differences among the scenarios. Only one pathway (S2, Full Integration) involves an international submarine cable, which is by far the largest single capital expenditure but also the most geopolitically complex. Three scenarios (S3, S4, S5) rely entirely on domestic renewable energy resources, differing primarily in whether islands are interconnected or operate independently and whether solar is deployed on rooftops, ground-mount, or on nearby uninhabited islands. S6 pushes the technological frontier by adding floating solar panels in lagoons and shallow waters. S7 introduces LNG as a transitional fuel for the largest demand centre. Each scenario is designed to answer a different strategic question: Can the Maldives go it alone with domestic renewables? Does the India cable add enough value to justify its cost and risk? Is LNG a sensible bridge fuel? How much solar can realistically be deployed given land constraints?\n\n## S1 — BAU: Continued Diesel {#sec-s1}\n\nThe business-as-usual scenario serves as the analytical counterfactual against which all alternatives are measured. Under this pathway, the Maldives continues expanding diesel generation capacity in step with demand growth, making no new renewable energy investments beyond those already committed in the existing pipeline. Every island maintains its current diesel-based power system, with new generators added as demand dictates.\n\nIt is important to emphasise that BAU is not a realistic projection of what will actually happen — even the Government of Maldives' own Energy Roadmap [-@gom_roadmap2024] envisions significant renewable energy deployment in the coming decade. Rather, BAU exists as the analytical baseline: it defines what the Maldives would spend, emit, and endure if no policy action were taken. By comparing each alternative against this counterfactual, the analysis isolates the incremental costs and benefits attributable to each transition pathway.\n\n::: {.callout-warning}\nBAU is not a realistic future — it represents *what happens if no policy action is taken*. It exists as the analytical baseline against which all alternatives are measured.\n:::\n\nThe BAU scenario assumes that electricity demand grows at 5 per cent per year, consistent with the historical compound annual growth rate observed in national statistics^[@irena_roadmap_maldives2015; STELCO Annual Reports confirm CAGR of approximately 5%.]. Diesel fuel is projected to cost $0\\.85 per litre in 2026 and escalate at 2 per cent per year in real terms, reflecting long-run trends in global petroleum markets^[See [Appendix B](B-parameters.qmd) for fuel price source and sensitivity range.]. No new solar or battery capacity is deployed, and all externalities — carbon emissions, health damages from air pollution, environmental costs — accumulate at the full diesel intensity throughout the analysis period. The result is a pathway of steadily rising costs, growing emissions, and deepening import dependence that serves as a stark illustration of the cost of inaction.\n\n## S2 — Full Integration: The India Cable {#sec-s2}\n\n\n\nThe Full Integration scenario is the most ambitious and most controversial pathway under consideration. It centres on the construction of a 700-kilometre high-voltage direct current (HVDC) submarine cable connecting the Maldives to India's national electricity grid^[@osowog2023; cable route distance estimated from Kanyakumari, India to Malé.]. This cable would provide imported electricity to Greater Malé at an estimated cost of $0\\.06/kWh^[@iea_india2023; reflecting the Indian wholesale electricity price plus a cross-border transmission premium.], reflecting the Indian wholesale electricity price plus a cross-border transmission premium. The outer islands, which are too distant from the cable route to be directly connected, would still receive solar-plus-battery systems similar to those in the other renewable-focused scenarios.\n\nThe investment required for this pathway is approximately $2\\.9 billion in additional capital expenditure relative to BAU, making it by far the most capital-intensive option. This total comprises the submarine cable itself (the single most expensive infrastructure element in any scenario), HVDC converter stations at both ends, landing station infrastructure, and the grid upgrades needed within the Maldives to distribute imported power. The NPV savings relative to diesel BAU amount to $9\\.5 billion, demonstrating that even with its enormous upfront cost, the cable pathway is economically superior to continued diesel dependence.\n\nThe case for the India cable rests on several arguments. It provides stable, reliable baseload power to Greater Malé, which accounts for 57 per cent of national demand and is severely constrained in its ability to deploy rooftop solar due to extreme urban density. The Indian grid's emission factor, currently 0\\.70 kgCO₂/kWh^[@iea_india2023.], is lower than diesel and declining at approximately 2 per cent per year as India adds renewable capacity, meaning that imported electricity becomes progressively cleaner over time. The cable also eliminates direct fuel import dependency, albeit by replacing it with electricity import dependency.\n\nHowever, the cable carries significant risks that merit careful consideration. The outage rate for comparable submarine cables (based on operational data from the NorNed and Basslink cables^[NorNed: 580 km North Sea cable, operational since 2008; Basslink: 290 km Bass Strait cable, operational since 2006. Combined operational record yields λ ≈ 0.15 faults per year.]) is approximately 0.15 per year, with repair times ranging from one to six months depending on the fault location and season. This creates a single-point-of-failure vulnerability that would require the Maldives to maintain substantial backup diesel capacity — partially undermining the fuel savings that justify the cable. The geopolitical dimension is also important: the Maldives would become dependent on a single foreign supplier for more than half its electricity, a relationship that inevitably carries diplomatic leverage implications. Finally, no cost-sharing agreement exists between the two countries. The base case assumes the Maldives bears 100 per cent of the cable cost, though sensitivity analysis explores a 50 per cent cost-sharing arrangement.\n\n## S3 — National Grid: Domestic RE with Interconnection {#sec-s3}\n\n\n\nThe National Grid scenario pursues full domestic energy independence through solar-plus-battery deployment across all islands, complemented by limited inter-island cable connections totalling 14 kilometres that link the three islands nearest to Malé. There is no international submarine cable, no LNG terminal, and no reliance on any external energy source. Greater Malé is constrained to approximately 18 MWp of rooftop solar, reflecting the limited available roof area identified in the @znes_flensburg study (5 MWp on public buildings plus 13 MWp on sports and community facilities).\n\nThe total additional CAPEX required is approximately $1\\.0 billion, and the pathway delivers $10\\.3 billion in NPV savings relative to diesel BAU. The technology assignment across islands is optimised by the model's least-cost electrification engine, which computes the discounted LCOE for each technology option on each island, taking into account island-specific solar resources, land availability, demand levels, and the cost of inter-island submarine cable connections where they are economically justified.\n\nThe principal advantage of this scenario is its maximisation of domestic energy independence. The Maldives controls its entire energy supply chain, from solar panels and batteries purchased on competitive international markets to locally managed generation and distribution. This eliminates both the geopolitical risks of the India cable and the fuel price volatility of continued diesel or LNG dependence. The modular nature of solar-plus-battery deployment also means that the transition can proceed island by island, with early deployments generating fuel savings that help finance later phases.\n\n## S4 — Islanded Green: Solar+Battery on Every Island {#sec-s4}\n\n\n\nThe Islanded Green scenario represents the simplest and most implementable pathway. Each island receives its own solar-plus-battery system, sized to meet its specific demand profile and constrained by its available land area. There are no inter-island cables, no submarine infrastructure of any kind, and no international dependencies. Each island's power system remains independent, replacing diesel with solar generation and battery storage while retaining diesel backup for periods of low solar output or unusually high demand.\n\nThe total additional investment required is approximately $1\\.2 billion, and the pathway generates $9\\.5 billion in NPV savings versus diesel BAU. This scenario scores highest among all alternatives on implementation feasibility in the multi-criteria analysis (MCA score 0.80), reflecting its use of proven, commercially available technology that can be deployed without complex inter-island coordination, regulatory reform, or international negotiations. It is also the most equitable pathway in geographic terms: every island receives investment, and every community benefits from reduced diesel dependence and improved air quality.\n\nThe trade-off is that this approach does not capture the cost efficiencies that might be available through interconnection or centralised large-scale generation. The island-specific logistics of transporting, installing, and maintaining solar panels and batteries across 187 separate sites carry a cost premium estimated at approximately 30 per cent relative to mainland-equivalent installations^[@irena_sids2023; @atlantic_council2024 confirm SIDS logistics premiums of 20–40%.]. Greater Malé, with its extremely limited rooftop area, achieves only modest solar penetration (approximately 18 MWp), leaving the capital region with the highest remaining diesel share among all renewable-focused scenarios.\n\n## S5 — Near-Shore Solar: Uninhabited Island Solar Farms {#sec-s5}\n\n\n\nThe Near-Shore Solar scenario directly addresses the most binding constraint on Greater Malé's energy transition: the lack of available land for solar deployment on one of the most densely populated islands in the world. This pathway deploys 104 MW of solar capacity on uninhabited islands located within 10 kilometres of Malé — specifically Thilafushi (a reclaimed industrial island), Gulhifalhu (under development for port and industrial use), Funadhoo, and Dhoonidhoo. These solar farms are connected to Greater Malé via short submarine cables, creating in effect a near-shore solar supply zone for the capital.\n\nThe total additional CAPEX is approximately $1\\.2 billion, with NPV savings of $11\\.1 billion relative to diesel BAU. The key innovation of this pathway is that it raises Greater Malé's renewable energy penetration from the approximately 4 per cent achievable through rooftop solar alone to roughly 25 per cent, without requiring any international infrastructure or geopolitical agreements. The outer islands receive standard solar-plus-battery deployments as in the other scenarios.\n\nThis scenario occupies a strategically interesting middle ground between the minimal-infrastructure Islanded Green pathway and the capital-intensive Full Integration or Maximum RE options. It captures a substantial share of the available solar benefit for Greater Malé at a fraction of the cost and risk of the India cable, while remaining entirely within the Maldives' sovereign control. The near-shore sites offer large land areas with minimal competing uses, good solar exposure, and proximity to the main demand centre. The principal implementation challenges are environmental permitting (particularly for Funadhoo and Dhoonidhoo, which may have ecological sensitivities), land tenure arrangements, and the engineering of short inter-island submarine cables in shallow reef waters.\n\n## S6 — Maximum RE: Floating Solar and Beyond {#sec-s6}\n\n\n\nThe Maximum RE scenario is the most technologically ambitious domestic pathway. It combines every available renewable energy option: rooftop solar on all islands, ground-mount solar where land permits, the 104 MW near-shore solar farms from S5, and an additional 195 MW of floating solar panels deployed on lagoons and shallow waters — 100 MW in the Greater Malé lagoon and 95 MW across outer atoll lagoons. This floating solar target is aligned with the @gom_roadmap2024, which identifies 195 MW of floating solar as a key component of the national transition strategy.\n\nThe total additional CAPEX is approximately $1\\.5 billion, generating NPV savings of $12\\.2 billion. This pathway achieves the highest final renewable energy share among all scenarios, pushing solar penetration to levels that would make the Maldives one of the most renewable-energy-intensive nations in the world. The environmental and energy security benefits are correspondingly large: minimal diesel dependence, near-zero domestic electricity emissions, and complete independence from foreign energy suppliers.\n\nThe additional cost of floating solar is significant — marine installation, anchoring systems, corrosion-resistant components, and the engineering challenges of tropical ocean environments add a premium of approximately 50 per cent over equivalent ground-mounted capacity. This technology is commercially available but has not yet been deployed at scale in tropical marine environments, introducing technical risk that the other scenarios largely avoid. The scenario therefore represents a calculated bet that floating solar technology will mature rapidly and that the cost premium will narrow as deployment experience accumulates. If the technology performs as expected, Maximum RE delivers the deepest decarbonisation and the greatest long-term fuel independence. If it underperforms, the fallback position is still strong: the near-shore and rooftop solar components deliver substantial benefits regardless of floating solar outcomes.\n\n## S7 — LNG Transition: Gas for Malé, Solar for Islands {#sec-s7}\n\n\n\nThe LNG Transition scenario introduces a fundamentally different approach for the Greater Malé region: replacing diesel generation with a 140 MW liquefied natural gas terminal at Gulhifalhu, operational from 2031. LNG combustion produces an emission factor of approximately 0\\.40 kgCO₂/kWh^[@ipcc2006; natural gas emission factor adjusted for combined-cycle efficiency.], which is 44 per cent lower than diesel, and the delivered cost of LNG-generated electricity is substantially below diesel at current and projected fuel prices. The outer islands follow the same solar-plus-battery pathway as in the other scenarios.\n\nThe total additional CAPEX is approximately $1\\.3 billion, with NPV savings of $12\\.2 billion. This scenario achieves the fastest payback period (7 years) and the highest internal rate of return (41\\.3 per cent) among all alternatives, reflecting the combination of relatively modest upfront capital requirements and immediate, large fuel cost savings as expensive diesel is replaced by cheaper gas.\n\nThe appeal of LNG is its pragmatism: it uses proven technology, leverages planned infrastructure at Gulhifalhu, and delivers rapid economic returns that can build political support for the broader transition. Gas-fired power also provides flexible, dispatchable baseload that complements intermittent solar generation, avoiding the battery storage costs that weigh on purely renewable pathways.\n\nThe fundamental concern with LNG, however, is fossil fuel lock-in. A 140 MW LNG terminal represents a 30-year commitment to gas infrastructure, with associated supply contracts, terminal maintenance obligations, and sunk costs that create strong institutional inertia against future displacement by renewables. The Maldives would exchange one form of fossil fuel dependence (diesel) for another (LNG), and while LNG is cleaner and cheaper, it does not deliver the deep decarbonisation or energy independence that the renewable-only pathways achieve. Global LNG markets are also subject to price volatility, as the 2022 energy crisis demonstrated when European demand spikes drove LNG spot prices to unprecedented levels.\n\n## Scenario Comparison Matrix\n\nThe bubble chart below provides a visual synthesis of how the seven scenarios compare along two of the most important dimensions: cumulative emissions (horizontal axis, with lower emissions to the right) and NPV savings relative to diesel BAU (vertical axis, with higher savings toward the top). The size of each bubble is proportional to the total capital expenditure required, allowing the reader to see at a glance which pathways achieve the largest economic and environmental benefits and at what investment cost.\n\n::: {#fig-scenario-matrix .cell execution_count=9}\n\n::: {#fig-scenario-matrix-1 .cell-output .cell-output-display}\n```{=html}\n        <script type=\"text/javascript\">\n        window.PlotlyConfig = {MathJaxConfig: 'local'};\n        if (window.MathJax && window.MathJax.Hub && window.MathJax.Hub.Config) {window.MathJax.Hub.Config({SVG: {font: \"STIX-Web\"}});}\n        </script>\n        <script type=\"module\">import \"https://cdn.plot.ly/plotly-3.0.1.min\"</script>\n        \n```\n\nScenario positioning on cost vs. emissions dimensions. Bubble size represents total CAPEX.\n:::\n\n::: {#fig-scenario-matrix-2 .cell-output .cell-output-display}\n```{=html}\n<div>            <script src=\"https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_SVG\"></script><script type=\"text/javascript\">if (window.MathJax && window.MathJax.Hub && window.MathJax.Hub.Config) {window.MathJax.Hub.Config({SVG: {font: \"STIX-Web\"}});}</script>                <script type=\"text/javascript\">window.PlotlyConfig = {MathJaxConfig: 'local'};</script>\n        <script charset=\"utf-8\" src=\"https://cdn.plot.ly/plotly-3.0.1.min.js\" integrity=\"sha256-oy6Be7Eh6eiQFs5M7oXuPxxm9qbJXEtTpfSI93dW16Q=\" crossorigin=\"anonymous\"></script>                <div id=\"0524bb32-ec84-4b76-a940-7b1f0e7717a3\" class=\"plotly-graph-div\" style=\"height:500px; width:100%;\"></div>            <script type=\"text/javascript\">                window.PLOTLYENV=window.PLOTLYENV || {};                                if (document.getElementById(\"0524bb32-ec84-4b76-a940-7b1f0e7717a3\")) {                    Plotly.newPlot(                        \"0524bb32-ec84-4b76-a940-7b1f0e7717a3\",                        [{\"marker\":{\"color\":\"#6c757d\",\"line\":{\"color\":\"white\",\"width\":1},\"opacity\":0.8,\"size\":14.930250000000001},\"mode\":\"markers+text\",\"name\":\"S1 BAU\",\"showlegend\":false,\"text\":[\"S1 BAU\"],\"textposition\":\"top center\",\"x\":[65.82970902000001],\"y\":[0.0],\"type\":\"scatter\"},{\"marker\":{\"color\":\"#0d6efd\",\"line\":{\"color\":\"white\",\"width\":1},\"opacity\":0.8,\"size\":53.34003764645515},\"mode\":\"markers+text\",\"name\":\"S2 FI\",\"showlegend\":false,\"text\":[\"S2 FI\"],\"textposition\":\"top center\",\"x\":[49.44432946325821],\"y\":[9.545066745209708],\"type\":\"scatter\"},{\"marker\":{\"color\":\"#198754\",\"line\":{\"color\":\"white\",\"width\":1},\"opacity\":0.8,\"size\":32.51928379668855},\"mode\":\"markers+text\",\"name\":\"S3 NG\",\"showlegend\":false,\"text\":[\"S3 NG\"],\"textposition\":\"top center\",\"x\":[33.164094432],\"y\":[10.333750789190189],\"type\":\"scatter\"},{\"marker\":{\"color\":\"#0dcaf0\",\"line\":{\"color\":\"white\",\"width\":1},\"opacity\":0.8,\"size\":37.25978498828873},\"mode\":\"markers+text\",\"name\":\"S4 IG\",\"showlegend\":false,\"text\":[\"S4 IG\"],\"textposition\":\"top center\",\"x\":[33.59930652],\"y\":[9.462209949100812],\"type\":\"scatter\"},{\"marker\":{\"color\":\"#fd7e14\",\"line\":{\"color\":\"white\",\"width\":1},\"opacity\":0.8,\"size\":35.7536336657154},\"mode\":\"markers+text\",\"name\":\"S5 NS\",\"showlegend\":false,\"text\":[\"S5 NS\"],\"textposition\":\"top center\",\"x\":[30.649919712000006],\"y\":[11.118095757160168],\"type\":\"scatter\"},{\"marker\":{\"color\":\"#ffc107\",\"line\":{\"color\":\"white\",\"width\":1},\"opacity\":0.8,\"size\":41.77566940443317},\"mode\":\"markers+text\",\"name\":\"S6 MR\",\"showlegend\":false,\"text\":[\"S6 MR\"],\"textposition\":\"top center\",\"x\":[26.619766511999995],\"y\":[12.156630522889731],\"type\":\"scatter\"},{\"marker\":{\"color\":\"#6f42c1\",\"line\":{\"color\":\"white\",\"width\":1},\"opacity\":0.8,\"size\":38.07381838352502},\"mode\":\"markers+text\",\"name\":\"S7 LNG\",\"showlegend\":false,\"text\":[\"S7 LNG\"],\"textposition\":\"top center\",\"x\":[33.393182576],\"y\":[12.202989280621427],\"type\":\"scatter\"}],                        {\"template\":{\"layout\":{\"colorway\":[\"#6c757d\",\"#0d6efd\",\"#198754\",\"#0dcaf0\",\"#fd7e14\",\"#ffc107\",\"#6f42c1\"],\"font\":{\"color\":\"#2c3e50\",\"family\":\"Inter, Segoe UI, Helvetica, sans-serif\",\"size\":13},\"legend\":{\"bgcolor\":\"rgba(255,255,255,0.9)\",\"bordercolor\":\"#dee2e6\",\"borderwidth\":1,\"font\":{\"size\":11}},\"margin\":{\"b\":50,\"l\":60,\"r\":30,\"t\":60},\"paper_bgcolor\":\"white\",\"plot_bgcolor\":\"#fafafa\",\"title\":{\"font\":{\"color\":\"#1a1a2e\",\"size\":18},\"x\":0.02,\"xanchor\":\"left\"},\"xaxis\":{\"gridcolor\":\"#e9ecef\",\"linecolor\":\"#dee2e6\",\"zerolinecolor\":\"#dee2e6\"},\"yaxis\":{\"gridcolor\":\"#e9ecef\",\"linecolor\":\"#dee2e6\",\"zerolinecolor\":\"#dee2e6\"}}},\"xaxis\":{\"title\":{\"text\":\"Cumulative Emissions (MtCO₂) — lower is better →\"},\"autorange\":\"reversed\"},\"title\":{\"text\":\"Scenario Positioning: Savings vs. Emissions\"},\"yaxis\":{\"title\":{\"text\":\"NPV Savings vs. BAU ($B) — higher is better →\"}},\"height\":500},                        {\"responsive\": true}                    ).then(function(){\n                            \nvar gd = document.getElementById('0524bb32-ec84-4b76-a940-7b1f0e7717a3');\nvar x = new MutationObserver(function (mutations, observer) {{\n        var display = window.getComputedStyle(gd).display;\n        if (!display || display === 'none') {{\n            console.log([gd, 'removed!']);\n            Plotly.purge(gd);\n            observer.disconnect();\n        }}\n}});\n\n// Listen for the removal of the full notebook cells\nvar notebookContainer = gd.closest('#notebook-container');\nif (notebookContainer) {{\n    x.observe(notebookContainer, {childList: true});\n}}\n\n// Listen for the clearing of the current output cell\nvar outputEl = gd.closest('.output');\nif (outputEl) {{\n    x.observe(outputEl, {childList: true});\n}}\n\n                        })                };            </script>        </div>\n```\n:::\n:::\n\n\nThe bubble chart reveals a clear pattern. The BAU scenario (S1) sits in the lower-left corner with zero savings and the highest emissions, while all six alternatives cluster in the upper portion of the chart with positive NPV savings. The highest-saving scenarios tend also to be the lowest-emitting ones, confirming that there is no fundamental tension between economic efficiency and environmental performance in this context — the cheapest pathways are also the cleanest. The size of the bubbles illustrates the capital investment trade-off: the India cable (S2) requires the largest upfront investment but does not consistently deliver the largest returns, while the domestically focused scenarios (S3, S4, S5) achieve large savings with more moderate capital requirements. The Maximum RE scenario (S6) pushes toward the frontier on both dimensions, achieving near-zero emissions with strong savings, though its bubble size reflects the premium cost of floating solar technology. The LNG scenario (S7) sits in an intermediate position on emissions — better than diesel but not as clean as the all-renewable pathways — while still achieving substantial savings.\n\nThe following chapters present the detailed economic results (@sec-results), test their robustness under parametric uncertainty (@sec-sensitivity), and extend the analysis beyond economic efficiency to encompass equity, institutional, and environmental dimensions (@sec-mca through @sec-financing).\n\n",
    "supporting": [
      "03-scenarios_files\\figure-html"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js\" integrity=\"sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js\" integrity=\"sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}