{
  "hash": "1c462aae3d5cb9fcc821be6df82a9b16",
  "result": {
    "engine": "jupyter",
    "markdown": "\n\n# Results {#sec-results}\n\n::: {.chapter-opening}\nThis chapter presents the core economic findings of the cost-benefit analysis. It examines the present-value costs, savings, benefit-cost ratios, levelised costs of electricity, and emissions trajectories for all seven scenarios, and provides a detailed incremental analysis comparing the India cable against domestic renewable alternatives.\n:::\n\n## The Big Picture: All Alternatives Beat Diesel\n\nThe most important finding of this analysis can be stated simply: every single alternative pathway generates billions of dollars in net economic benefits compared to continued diesel dependence. This result is not marginal or ambiguous — the savings are large, they are consistent across scenarios, and as demonstrated in @sec-sensitivity, they are robust to wide variation in key parameters.\n\n::: {.cell execution_count=2}\n\n::: {.cell-output .cell-output-display}\n![Net present value of savings versus BAU for each alternative scenario. All alternatives generate billions in net benefits.](04-results_files/figure-pdf/fig-npv-savings-output-1.png){#fig-npv-savings}\n:::\n:::\n\n\n\n\nThe figure above displays the net present value of savings for each alternative scenario relative to the diesel business-as-usual counterfactual. The results are unambiguous: every alternative saves the Maldives between $10\\.3 billion and $13\\.8 billion in present value over the 30-year analysis period. The S6 — Maximum RE scenario achieves the highest NPV savings, while even S4 — Islanded Green — the least advantageous alternative — delivers substantial net benefits. The magnitude of these savings reflects the enormous cumulative cost of diesel fuel over three decades, which dwarfs the upfront capital investment required for any of the transition pathways.\n\nIt is worth emphasising that these savings are calculated at a 6 per cent real discount rate, which heavily discounts benefits occurring in later years. At lower discount rates (3–4 per cent, as used by several OECD development agencies), the savings would be even larger, because the long tail of fuel cost avoidance in the 2040s and 2050s receives greater weight. Conversely, even at the high end of the ADB range (12 per cent), all alternatives still dominate diesel — the breakeven discount rate for every scenario is well above 0 per cent.\n\n## Cost Breakdown by Component\n\nUnderstanding *why* the alternatives are cheaper requires examining the composition of costs under each pathway. The stacked bar chart below decomposes the present value of total system costs into four components: capital expenditure (the upfront investment in solar panels, batteries, cables, generators, and other infrastructure), operating expenditure (annual maintenance, labour, and non-fuel running costs), fuel costs (diesel and LNG purchases), and power purchase agreement imports (the cost of electricity imported via the India cable).\n\n::: {.cell execution_count=4}\n\n::: {.cell-output .cell-output-display}\n![Present value of costs by component for each scenario. Fuel costs dominate BAU; CAPEX dominates alternatives but at lower total cost.](04-results_files/figure-pdf/fig-cost-breakdown-output-1.png){#fig-cost-breakdown}\n:::\n:::\n\n\nThe cost structure reveals a fundamental shift between diesel and renewable pathways. Under business-as-usual, the dominant cost component is fuel, which accounts for $14\\.4 billion or approximately 92 per cent of total lifetime system costs. This reflects the inherent economics of diesel generation: the capital cost of generators is relatively modest, but the ongoing fuel expenditure compounds relentlessly over 30 years, especially as diesel prices escalate and demand grows.\n\nThe renewable scenarios invert this cost structure. Capital expenditure — for solar panels, battery systems, and in some cases submarine cables and LNG terminals — becomes the dominant cost component, while fuel costs shrink dramatically or disappear entirely. The critical insight is that even though the upfront CAPEX of the renewable pathways is higher than the BAU generator replacement cost, the total lifetime system cost is substantially lower because the avoided fuel expenditure far outweighs the additional capital investment. Solar panels and batteries, once installed, generate electricity at near-zero marginal cost for decades, whereas diesel generators require a continuous stream of expensive imported fuel.\n\nThe Full Integration scenario (S2) is unique in exhibiting significant PPA import costs alongside CAPEX, reflecting the ongoing payments for electricity imported through the India cable. While these import costs are far lower than the diesel fuel costs they displace, they represent a continuing outflow that the purely domestic renewable scenarios avoid entirely.\n\n### Why Fuel Costs Remain Substantial Even Under Renewable Scenarios {#sec-fuel-persistence}\n\n\n\nA natural question arises from @fig-cost-breakdown: if all alternative scenarios involve substantial renewable energy investment, why does fuel still constitute between 26 and 74 per cent of total lifetime costs in the domestic scenarios (S3–S7)? The answer lies in a set of binding physical, geographic, and technical constraints that limit the achievable renewable energy penetration on small coral islands.\n\n**Land scarcity.** The most fundamental constraint is that the Maldives has only 134 km² of total inhabited island area, spread across nearly 200 islands. Solar PV requires approximately 7 m² per installed kW (including panel spacing and access), and the model caps the usable share of island area at 15 per cent to preserve land for housing, agriculture, vegetation, and public use. On the smallest and most densely populated islands, solar demand for space exceeds this limit, forcing them into diesel-hybrid configurations regardless of economics. Across all inhabited islands, this physical ceiling means that rooftop and ground-mount solar alone cannot supply the growing national demand.\n\n**The Malé bottleneck.** Greater Malé — comprising Malé, Hulhumalé, and Villimalé — consumes more than half of national electricity but is among the most densely built urban areas in the world. With limited available land, rooftop and commercial installations are capped at approximately 34 MWp, which can supply only about 8 per cent of Malé's demand^[ADB Energy Roadmap 2024–2033 (Table 8): 4 MW ASSURE rooftop + 5 MW additional rooftop + 25 MW commercial rooftop on Gulhifalhu/Thilafushi = 34 MWp total. This is nearly double the earlier ZNES Flensburg estimate of 18 MWp (public buildings and sports facilities only).]. Because Malé's demand share is so large, even if every outer island achieved 100 per cent renewable supply, the national weighted average would be constrained by Malé's limited rooftop potential. The Near-Shore Solar (S5) and Maximum RE (S6) scenarios exist specifically to break this bottleneck by siting 104 MW on uninhabited islands, 195 MW on floating platforms, and 80 MW of wind energy near Malé — which is why S6 achieves the highest final RE share at 64 per cent.\n\n**Deployment speed.** Even where economics and land permit, construction logistics impose a practical ceiling of 80 MW of new solar capacity per year nationally. The ADB Energy Roadmap 2024–2033 identifies a pipeline of 424 MW of planned and potential solar initiatives over five years (approximately 85 MW per year), which the model adopts as the base deployment pace. This reflects the realities of importing equipment to remote atolls, limited port capacity, skilled labour scarcity, and the sequential nature of island-by-island installation. Over the 30 year analysis period, cumulative installations are substantial, but growing demand (at approximately 5 per cent per year) constantly expands the denominator against which the RE share is measured.\n\nNote that the Government of Maldives targets **33 per cent** renewable energy in electricity consumption by 2028 (ADB Energy Roadmap 2024–2033), which requires approximately 800 GWh from renewable sources against projected demand of 2,400 GWh. The model's deployment trajectory is calibrated to this near-term target, and the scenarios explore what happens as the transition continues beyond 2028 toward 2056, with the ultimate RE share determined by the interplay of deployment speed, land constraints, and demand growth.\n\n**Storage duration.** Solar panels produce electricity for roughly six to eight hours per day, concentrated around midday. The model assumes 4 hours of battery storage per site, which covers the evening demand peak but cannot carry load through the entire night. With a maximum depth of discharge of 80 per cent and round-trip efficiency of 88 per cent, the usable energy per cycle is further reduced. Diesel backup therefore remains essential for overnight and extended cloudy-period generation. Increasing storage to eight or more hours would substantially raise RE penetration, but at current battery prices ($350/kWh installed), the cost of doubling storage duration exceeds the fuel savings it would displace.\n\n**The net effect** is that even the most ambitious technically feasible scenario (S6 Maximum RE) reaches only 64 per cent renewable penetration by 2056, while the more conservative pathways (S3, S4) plateau around 51 to 51 per cent. The remaining generation gap — ranging from 36 to 5 per cent — must be filled by diesel (or LNG in S7), and the cumulative fuel cost of that residual fossil generation over 30 years is what produces the large red bars visible in every scenario. This persistent fuel exposure is precisely why the sensitivity analysis (@sec-sensitivity) identifies diesel price as the single most influential parameter across all pathways: even after transition, the Maldives remains partially dependent on imported fuel, and the economic case for transition is strengthened — not weakened — by this reality, because the alternative is *total* dependence under BAU.\n\n## Renewable Energy Ceiling: Can the Maldives Reach 70–80 Per Cent? {#sec-re-ceiling}\n\n\n\nThe Government of Maldives' Energy Roadmap 2024–2033 [-@gom_roadmap2024] targets 33 per cent renewable energy by 2028. A question of significant policy interest is whether the Maldives can push further — to 70, 80, or even higher renewable energy shares by mid-century. The Maximum RE scenario (S6) provides the analytical framework to answer this question, and the results reveal both encouraging progress and sobering structural limits.\n\n::: {.cell execution_count=7}\n\n::: {.cell-output .cell-output-display}\n![Renewable energy share trajectory under Maximum RE (S6). RE peaks in the late 2030s before demand growth erodes the share.](04-results_files/figure-pdf/fig-re-trajectory-output-1.png){#fig-re-trajectory}\n:::\n:::\n\n\n@fig-re-trajectory reveals a striking and counterintuitive pattern: **the RE share does not rise monotonically** but instead peaks in the late 2030s before gradually declining. Under the Maximum RE scenario, renewable energy reaches approximately 87 per cent by 2035 and peaks around 72 per cent by 2040 — temporarily exceeding the 70 per cent threshold — before falling back to 44 per cent by 2050 and 64 per cent by 2056. This phenomenon occurs because renewable energy capacity is bounded by physical constraints (land area, deployment speed, technology availability), while electricity demand continues growing at approximately 5 per cent per year.\n\n### Supply-Side RE Potential\n\nThe Maximum RE scenario deploys every available domestic renewable energy technology:\n\n| Technology | Capacity | Annual Generation | Source |\n|---|---|---|---|\n| Rooftop solar (Malé) | 34 MWp | ~52 GWh | ADB Roadmap Table 8 |\n| Near-shore solar | 104 MW | ~159 GWh | Uninhabited islands |\n| Floating solar | 195 MW | ~299 GWh | GoM Roadmap target |\n| Wind energy | 80 MW | ~175 GWh | ADB Roadmap §4.7.2 |\n| Outer island solar | Variable | Growing with demand | Least-cost engine |\n| Waste-to-energy | 14 MW | ~98 GWh | Thilafushi facility |\n\nThe combined Malé-region RE potential (rooftop + near-shore + floating + wind) is approximately 413 MW, capable of generating roughly 686 GWh per year. This is substantial — but it is a *fixed ceiling*, while demand is an exponentially growing quantity.\n\n### The Demand Growth Denominator\n\nAt 5 per cent annual growth, national electricity demand roughly doubles every 14 years. By 2050, demand is projected to reach approximately 3\\,870 GWh — nearly four times the 2026 level. Even if every available renewable technology is deployed at maximum capacity, the fixed RE generation ceiling means that the *share* of renewable energy in total supply inevitably declines once the deployment programme is complete and demand continues growing.\n\nThis is the fundamental arithmetic challenge: **renewable capacity is area-constrained; electricity demand is not.** The Maldives cannot manufacture more island area, and floating solar and wind capacity — while helpful — are bounded by lagoon area, environmental constraints, and technical feasibility.\n\n### Pathways to Sustained 70 Per Cent or Higher\n\nSustaining RE penetration above 70 per cent beyond the 2040 window would require one or more of the following structural changes:\n\n1. **Demand moderation.** If demand growth were moderated to 3.5 per cent per year (the Low sensitivity case) rather than 5 per cent, 2050 demand would be approximately 2\\,740 GWh rather than 3\\,870 GWh — a reduction of 29 per cent that would sustain RE shares above 70 per cent for significantly longer. Energy efficiency standards, time-of-use pricing, and demand-side management programmes are the principal policy levers.\n\n2. **Floating solar expansion beyond 195 MW.** The current target of 195 MW is aligned with the GoM Roadmap, but the Maldives has approximately 26,000 km² of lagoon area, of which even 0.1 per cent utilisation would yield over 3,000 MW of potential. If floating solar technology matures and costs decline as projected, a second phase of 200–400 MW could substantially extend the RE ceiling. This remains speculative given the technology's immaturity in tropical marine environments.\n\n3. **Wind energy expansion.** The ADB Roadmap identifies 80 MW of wind potential, contributing approximately 175 GWh per year (roughly 4–5 percentage points of RE share). Scaling wind beyond 80 MW is constrained by the Maldives' relatively modest wind resources — capacity factors of 25 per cent are below the global average for onshore wind — but it provides valuable generation diversity (wind and solar have partially complementary diurnal profiles).\n\n4. **India submarine cable.** The Full Integration scenario (S2) achieves the highest *total* clean energy supply by importing grid electricity from India, but this reduces *domestic* RE share to approximately 11 per cent. Whether imported electricity counts toward RE targets depends on the carbon intensity of the Indian grid, which is currently 0\\.70 kgCO₂/kWh and declining.\n\n::: {.callout-important}\n## 70% RE is achievable but time-limited\nThe Maximum RE scenario demonstrates that 70 per cent renewable energy penetration is technically feasible and economically attractive in the late 2030s window. However, sustaining this level requires either moderating demand growth, expanding floating solar beyond current plans, or accepting that the Maldives' domestic RE share will plateau in the 60–65 per cent range by 2050 under base-case demand growth.\n:::\n\n## Benefit-Cost Ratios and Returns\n\nThe benefit-cost ratio and internal rate of return provide complementary perspectives on the economic attractiveness of each transition pathway. The BCR indicates the total present value of benefits generated per dollar of incremental cost, with any value above 1.0 indicating that the investment creates net value for society. The IRR identifies the discount rate at which the project breaks even, with values exceeding the 6 per cent hurdle rate confirming economic viability.\n\n::: {.cell execution_count=8}\n\n::: {.cell-output .cell-output-display}\n![Benefit-cost ratios (left) and internal rates of return (right) for each alternative scenario.](04-results_files/figure-pdf/fig-bcr-irr-output-1.png){#fig-bcr-irr}\n:::\n:::\n\n\nThe left panel shows that all six alternatives achieve BCRs well above the 1.0 threshold, meaning that society receives substantially more in benefits than it pays in costs under every transition pathway. The right panel shows that the IRR for every scenario exceeds the 6 per cent hurdle rate (indicated by the dashed red line), confirming that the transition investments would generate returns above the social opportunity cost of capital even under more conservative assumptions about the discount rate. The scenarios with the highest BCRs tend to be those that achieve the deepest displacement of diesel fuel, because the avoided fuel costs constitute the largest benefit stream. The LNG scenario (S7) achieves the highest IRR, reflecting its combination of relatively modest CAPEX and rapid, large fuel cost savings from replacing expensive diesel with cheaper gas — even though it does not achieve the highest absolute NPV savings.\n\nThe full results table below consolidates all key metrics for ready comparison across scenarios.\n\n::: {#tbl-results-summary .cell tbl-cap='Full scenario comparison table: costs, savings, returns, emissions.' execution_count=9}\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=9}\n| Scenario   | PV Total Costs ($B)   | LCOE ($/kWh)   | NPV Savings ($B)   | BCR   | IRR (%)   | Payback (yr)   |   Emissions (MtCO₂) | Final RE (%)   |\n|:-----------|:----------------------|:---------------|:-------------------|:------|:----------|:---------------|--------------------:|:---------------|\n| S1 BAU     | $15.7                 | $0.437         | —                  | —     | —         | —              |                65.8 | 1%             |\n| S2 FI      | $9.0                  | $0.204         | $10.3              | 2.9×  | 17.0%     | 13             |                46   | 11%            |\n| S3 NG      | $8.6                  | $0.273         | $11.3              | 12.4× | 38.7%     | 6              |                31.4 | 51%            |\n| S4 IG      | $9.6                  | $0.304         | $10.3              | 8.4×  | 29.4%     | 8              |                31.5 | 51%            |\n| S5 NS      | $8.3                  | $0.263         | $12.0              | 11.0× | 37.6%     | 7              |                28.9 | 54%            |\n| S6 MR      | $7.3                  | $0.234         | $13.8              | 9.1×  | 36.5%     | 7              |                21.7 | 64%            |\n| S7 LNG     | $7.2                  | $0.200         | $13.3              | 11.5× | 44.2%     | 6              |                30   | 47%            |\n:::\n:::\n\n\nThe summary table reinforces the central finding that every alternative pathway is economically superior to continued diesel dependence, and it allows the reader to see the trade-offs among them. The scenarios with the highest renewable energy shares tend to deliver the largest NPV savings, the lowest LCOE, and the deepest emissions reductions, but they may also require more capital and involve greater technological risk (as with floating solar in S6). The LNG scenario stands out for its combination of fast payback and high IRR, which reflects its bridging character — it achieves rapid cost savings by swapping one fossil fuel for a cheaper one, rather than by fundamentally transforming the technology base.\n\n## LCOE Comparison\n\nThe levelised cost of electricity provides the most intuitive metric for comparing generation costs across technologies and scenarios. Unlike total system cost or NPV, which are sensitive to demand projections and discount rates, LCOE expresses the average cost of producing one unit of electricity over the project lifetime, making it directly comparable to retail tariffs, benchmark studies, and international experience.\n\n::: {.cell execution_count=10}\n\n::: {.cell-output .cell-output-display}\n![Levelised cost of electricity by scenario, with international benchmarks for context.](04-results_files/figure-pdf/fig-lcoe-output-1.png){#fig-lcoe}\n:::\n:::\n\n\nThe LCOE comparison chart places the Maldives scenarios in the context of international benchmarks. The diesel BAU LCOE substantially exceeds global diesel mini-grid averages, reflecting the particular cost penalties of small-island generation: fuel transport surcharges, scale inefficiencies of small generators, and high labour costs for maintenance on remote islands. The renewable-based scenarios achieve LCOEs that approach the SIDS average for renewable generation and, in some cases, come close to global utility-scale solar benchmarks — a remarkable achievement for a small island nation with severe logistical constraints. The gap between the BAU LCOE and the best alternative LCOEs represents the per-unit cost advantage of transition, which compounds into the billions of dollars of NPV savings documented above.\n\n## Emissions Trajectories\n\nClimate impact is a critical dimension of the energy transition decision, both because the Maldives has committed to ambitious emissions reduction targets under the Paris Agreement and because, as the world's lowest-lying nation, it has an existential stake in global climate action. The figure below compares cumulative CO₂ emissions across all seven scenarios over the 30-year analysis period.\n\n::: {.cell execution_count=11}\n\n::: {.cell-output .cell-output-display}\n![Cumulative CO₂ emissions by scenario. All alternatives achieve significant emission reductions versus diesel BAU.](04-results_files/figure-pdf/fig-emissions-output-1.png){#fig-emissions}\n:::\n:::\n\n\n\n\nThe emissions comparison reveals the enormous environmental dividend of transition. Under diesel BAU, the Maldives electricity sector would emit 65\\.8 million tonnes of CO₂ over the 30-year period. The cleanest scenario, S6 MR, reduces cumulative emissions by 67 per cent to just 21\\.7 million tonnes. Even the scenarios that retain some fossil fuel component — such as the LNG Transition (S7), which achieves a 44 per cent reduction in emission intensity by switching from diesel to natural gas — deliver substantial climate benefits relative to the status quo.\n\nThe emissions ranking does not perfectly mirror the economic ranking, which creates an interesting policy tension. Some scenarios that are slightly less cost-optimal deliver substantially deeper decarbonisation, meaning that policymakers face a genuine choice about how much additional cost (if any) they are willing to accept to achieve greater emissions reduction. However, the trade-off is modest: the cost difference between the most economically efficient scenario and the most environmentally ambitious one is small relative to the savings both deliver versus diesel.\n\n## The India Cable vs. Domestic Alternatives\n\nA question of particular strategic importance is whether the India submarine cable (S2) justifies its substantial cost premium over domestic renewable alternatives. While the cable clearly dominates diesel BAU (as do all alternatives), the relevant policy comparison is against the next-best option that does not require international infrastructure. The incremental analysis comparing S2 (Full Integration) against S3 (National Grid, the best domestic alternative) directly addresses this question.\n\n\n\nThe incremental analysis reveals that the India cable requires $2\\.0B in additional capital expenditure beyond what the National Grid domestic scenario would cost. This additional investment yields an incremental benefit-cost ratio of only 0\\.78, which falls below the 1.0 threshold — meaning that the marginal costs of the cable exceed its marginal benefits relative to domestic solar-plus-battery. The incremental IRR of 1\\.2 per cent is below the 6 per cent social discount rate, and the incremental payback period extends to 22 years, raising questions about the cable's economic justification on the margin.\n\n::: {.callout-important}\n## The cable does not pay for itself on the margin\nWhile S2 saves money versus *diesel* (BCR 2\\.9 ×), it does *not* save money versus *domestic solar+battery* (S3). The cable's marginal BCR of 0\\.78 means that every additional dollar invested in the cable yields only 78 cents of additional benefit. Domestic RE is more cost-effective.\n:::\n\nThis finding does not categorically rule out the India cable — there may be strategic, geopolitical, or energy security arguments that fall outside the scope of economic CBA. However, it does establish that from a pure cost-effectiveness standpoint, the Maldives would be better served by investing the same capital in domestic solar, battery, and near-shore solar capacity. The cable's marginal economics would improve if India were to share the construction cost (the sensitivity analysis explores a 50 per cent cost-sharing scenario), if Indian electricity export prices were lower than assumed, or if domestic solar deployment encountered unforeseen cost escalation. These conditions are possible but uncertain, which reinforces the real-options argument for deferring the cable decision presented in @sec-real-options.\n\n",
    "supporting": [
      "04-results_files"
    ],
    "filters": []
  }
}