<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>6&nbsp; Results – Energy Transition Pathways for the Maldives</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./05-sensitivity.html" rel="next">
<link href="./03-scenarios.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-0cda1927dbbec9a6c1082bdc957d5e43.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>
<style>
.callout-note { border-left-color: #0d6efd !important; }
.callout-important { border-left-color: #dc3545 !important; }
.callout-tip { border-left-color: #198754 !important; }
</style>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./04-results.html">Part II — Results</a></li><li class="breadcrumb-item"><a href="./04-results.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Results</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Energy Transition Pathways for the Maldives</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">About This Report</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./executive-summary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Executive Summary</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Part I — Context &amp; Approach</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-methodology.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Methodology</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-scenarios.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">The Seven Scenarios</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Part II — Results</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-results.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Results</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-sensitivity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Sensitivity &amp; Robustness</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-mca.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Multi-Criteria Analysis</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Part III — Policy Implications</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-distributional.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Distributional Analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-financing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Financing</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-implementation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Implementation Roadmap</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-conclusions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Conclusions &amp; Recommendations</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./A-methodology-detail.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Appendix A — Technical Methodology</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./B-parameters.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Appendix B — Complete Parameter Table</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./C-supplementary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Appendix C — Supplementary Analyses</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#the-big-picture-all-alternatives-beat-diesel" id="toc-the-big-picture-all-alternatives-beat-diesel" class="nav-link active" data-scroll-target="#the-big-picture-all-alternatives-beat-diesel"><span class="header-section-number">6.1</span> The Big Picture: All Alternatives Beat Diesel</a></li>
  <li><a href="#cost-breakdown-by-component" id="toc-cost-breakdown-by-component" class="nav-link" data-scroll-target="#cost-breakdown-by-component"><span class="header-section-number">6.2</span> Cost Breakdown by Component</a>
  <ul class="collapse">
  <li><a href="#sec-fuel-persistence" id="toc-sec-fuel-persistence" class="nav-link" data-scroll-target="#sec-fuel-persistence"><span class="header-section-number">6.2.1</span> Why Fuel Costs Remain Substantial Even Under Renewable Scenarios</a></li>
  </ul></li>
  <li><a href="#benefit-cost-ratios-and-returns" id="toc-benefit-cost-ratios-and-returns" class="nav-link" data-scroll-target="#benefit-cost-ratios-and-returns"><span class="header-section-number">6.3</span> Benefit-Cost Ratios and Returns</a></li>
  <li><a href="#lcoe-comparison" id="toc-lcoe-comparison" class="nav-link" data-scroll-target="#lcoe-comparison"><span class="header-section-number">6.4</span> LCOE Comparison</a></li>
  <li><a href="#emissions-trajectories" id="toc-emissions-trajectories" class="nav-link" data-scroll-target="#emissions-trajectories"><span class="header-section-number">6.5</span> Emissions Trajectories</a></li>
  <li><a href="#the-india-cable-vs.-domestic-alternatives" id="toc-the-india-cable-vs.-domestic-alternatives" class="nav-link" data-scroll-target="#the-india-cable-vs.-domestic-alternatives"><span class="header-section-number">6.6</span> The India Cable vs.&nbsp;Domestic Alternatives</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./04-results.html">Part II — Results</a></li><li class="breadcrumb-item"><a href="./04-results.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Results</span></a></li></ol></nav>
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title"><span id="sec-results" class="quarto-section-identifier"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Results</span></span></h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="chapter-opening">
<p>This chapter presents the core economic findings of the cost-benefit analysis. It examines the present-value costs, savings, benefit-cost ratios, levelised costs of electricity, and emissions trajectories for all seven scenarios, and provides a detailed incremental analysis comparing the India cable against domestic renewable alternatives.</p>
</div>
<section id="the-big-picture-all-alternatives-beat-diesel" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="the-big-picture-all-alternatives-beat-diesel"><span class="header-section-number">6.1</span> The Big Picture: All Alternatives Beat Diesel</h2>
<p>The most important finding of this analysis can be stated simply: every single alternative pathway generates billions of dollars in net economic benefits compared to continued diesel dependence. This result is not marginal or ambiguous — the savings are large, they are consistent across scenarios, and as demonstrated in <a href="05-sensitivity.html" class="quarto-xref"><span>Chapter 8</span></a>, they are robust to wide variation in key parameters.</p>
<div class="cell" data-execution_count="2">
<div id="fig-npv-savings" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="2">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-npv-savings-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div id="fig-npv-savings-1" class="cell-output cell-output-display quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-npv-savings-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
        <script type="text/javascript">
        window.PlotlyConfig = {MathJaxConfig: 'local'};
        if (window.MathJax && window.MathJax.Hub && window.MathJax.Hub.Config) {window.MathJax.Hub.Config({SVG: {font: "STIX-Web"}});}
        </script>
        <script type="module">import "https://cdn.plot.ly/plotly-3.0.1.min"</script>
        
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-npv-savings-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) Net present value of savings versus BAU for each alternative scenario. All alternatives generate billions in net benefits.
</figcaption>
</figure>
</div>
<div id="fig-npv-savings-2" class="cell-output cell-output-display quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-npv-savings-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div>            <script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_SVG"></script><script type="text/javascript">if (window.MathJax && window.MathJax.Hub && window.MathJax.Hub.Config) {window.MathJax.Hub.Config({SVG: {font: "STIX-Web"}});}</script>                <script type="text/javascript">window.PlotlyConfig = {MathJaxConfig: 'local'};</script>
        <script charset="utf-8" src="https://cdn.plot.ly/plotly-3.0.1.min.js" integrity="sha256-oy6Be7Eh6eiQFs5M7oXuPxxm9qbJXEtTpfSI93dW16Q=" crossorigin="anonymous"></script>                <div id="33e9e604-0950-4007-ba87-0553532be4f0" class="plotly-graph-div" style="height:420px; width:100%;"></div>            <script type="text/javascript">                window.PLOTLYENV=window.PLOTLYENV || {};                                if (document.getElementById("33e9e604-0950-4007-ba87-0553532be4f0")) {                    Plotly.newPlot(                        "33e9e604-0950-4007-ba87-0553532be4f0",                        [{"marker":{"color":["#0d6efd","#198754","#0dcaf0","#fd7e14","#ffc107","#6f42c1"]},"text":["10","11","10","12","13","13"],"textposition":"outside","x":["S2 FI","S3 NG","S4 IG","S5 NS","S6 MR","S7 LNG"],"y":[10.039779717706296,10.96699220689325,9.931912054087016,11.61865064830705,12.587333786062889,12.985040015275075],"type":"bar"}],                        {"template":{"layout":{"colorway":["#6c757d","#0d6efd","#198754","#0dcaf0","#fd7e14","#ffc107","#6f42c1"],"font":{"color":"#2c3e50","family":"Inter, Segoe UI, Helvetica, sans-serif","size":13},"legend":{"bgcolor":"rgba(255,255,255,0.9)","bordercolor":"#dee2e6","borderwidth":1,"font":{"size":11}},"margin":{"b":50,"l":60,"r":30,"t":60},"paper_bgcolor":"white","plot_bgcolor":"#fafafa","title":{"font":{"color":"#1a1a2e","size":18},"x":0.02,"xanchor":"left"},"xaxis":{"gridcolor":"#e9ecef","linecolor":"#dee2e6","zerolinecolor":"#dee2e6"},"yaxis":{"gridcolor":"#e9ecef","linecolor":"#dee2e6","zerolinecolor":"#dee2e6"}}},"title":{"text":"NPV Savings vs. Diesel BAU ($ Billions)"},"yaxis":{"title":{"text":"NPV Savings ($B)"}},"xaxis":{"title":{"text":""}},"height":420,"showlegend":false},                        {"responsive": true}                    ).then(function(){
                            
var gd = document.getElementById('33e9e604-0950-4007-ba87-0553532be4f0');
var x = new MutationObserver(function (mutations, observer) {{
        var display = window.getComputedStyle(gd).display;
        if (!display || display === 'none') {{
            console.log([gd, 'removed!']);
            Plotly.purge(gd);
            observer.disconnect();
        }}
}});

// Listen for the removal of the full notebook cells
var notebookContainer = gd.closest('#notebook-container');
if (notebookContainer) {{
    x.observe(notebookContainer, {childList: true});
}}

// Listen for the clearing of the current output cell
var outputEl = gd.closest('.output');
if (outputEl) {{
    x.observe(outputEl, {childList: true});
}}

                        })                };            </script>        </div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-npv-savings-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b)
</figcaption>
</figure>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-npv-savings-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.1
</figcaption>
</figure>
</div>
</div>
<p>The figure above displays the net present value of savings for each alternative scenario relative to the diesel business-as-usual counterfactual. The results are unambiguous: every alternative saves the Maldives between $9.9 billion and $13.0 billion in present value over the 30-year analysis period. The S7 — LNG Transition scenario achieves the highest NPV savings, while even S4 — Islanded Green — the least advantageous alternative — delivers substantial net benefits. The magnitude of these savings reflects the enormous cumulative cost of diesel fuel over three decades, which dwarfs the upfront capital investment required for any of the transition pathways.</p>
<p>It is worth emphasising that these savings are calculated at a 6 per cent real discount rate, which heavily discounts benefits occurring in later years. At lower discount rates (3–4 per cent, as used by several OECD development agencies), the savings would be even larger, because the long tail of fuel cost avoidance in the 2040s and 2050s receives greater weight. Conversely, even at the high end of the ADB range (12 per cent), all alternatives still dominate diesel — the breakeven discount rate for every scenario is well above 0 per cent.</p>
</section>
<section id="cost-breakdown-by-component" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="cost-breakdown-by-component"><span class="header-section-number">6.2</span> Cost Breakdown by Component</h2>
<p>Understanding <em>why</em> the alternatives are cheaper requires examining the composition of costs under each pathway. The stacked bar chart below decomposes the present value of total system costs into four components: capital expenditure (the upfront investment in solar panels, batteries, cables, generators, and other infrastructure), operating expenditure (annual maintenance, labour, and non-fuel running costs), fuel costs (diesel and LNG purchases), and power purchase agreement imports (the cost of electricity imported via the India cable).</p>
<div id="cell-fig-cost-breakdown" class="cell" data-execution_count="4">
<div id="fig-cost-breakdown" class="cell-output cell-output-display quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cost-breakdown-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div>            <script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_SVG"></script><script type="text/javascript">if (window.MathJax && window.MathJax.Hub && window.MathJax.Hub.Config) {window.MathJax.Hub.Config({SVG: {font: "STIX-Web"}});}</script>                <script type="text/javascript">window.PlotlyConfig = {MathJaxConfig: 'local'};</script>
        <script charset="utf-8" src="https://cdn.plot.ly/plotly-3.0.1.min.js" integrity="sha256-oy6Be7Eh6eiQFs5M7oXuPxxm9qbJXEtTpfSI93dW16Q=" crossorigin="anonymous"></script>                <div id="7b7244e0-bd85-4ea6-99b2-98f2b9e9b902" class="plotly-graph-div" style="height:480px; width:100%;"></div>            <script type="text/javascript">                window.PLOTLYENV=window.PLOTLYENV || {};                                if (document.getElementById("7b7244e0-bd85-4ea6-99b2-98f2b9e9b902")) {                    Plotly.newPlot(                        "7b7244e0-bd85-4ea6-99b2-98f2b9e9b902",                        [{"marker":{"color":"#3498db"},"name":"CAPEX","x":["S1 BAU","S2 FI","S3 NG","S4 IG","S5 NS","S6 MR","S7 LNG"],"y":[0.5133098360743283,3.7082150642347256,1.6432917259427688,1.9589627725213345,1.8385331374281586,2.1180032416104693,1.9656502665488178],"type":"bar"},{"marker":{"color":"#2ecc71"},"name":"OPEX","x":["S1 BAU","S2 FI","S3 NG","S4 IG","S5 NS","S6 MR","S7 LNG"],"y":[0.8861975295689597,1.2281842566698418,0.8323967062239745,0.9008458495989958,0.8369344088131113,0.842911140306321,0.7789285381268954],"type":"bar"},{"marker":{"color":"#e74c3c"},"name":"Fuel","x":["S1 BAU","S2 FI","S3 NG","S4 IG","S5 NS","S6 MR","S7 LNG"],"y":[14.347724981245465,2.415261392266368,6.471935023209864,7.096449951175424,5.9775258961667666,5.238716951771864,4.831519571504652],"type":"bar"},{"marker":{"color":"#9b59b6"},"name":"PPA Imports","x":["S1 BAU","S2 FI","S3 NG","S4 IG","S5 NS","S6 MR","S7 LNG"],"y":[0.0,2.105449788550918,0.0,0.0,0.0,0.0,0.0],"type":"bar"}],                        {"template":{"layout":{"colorway":["#6c757d","#0d6efd","#198754","#0dcaf0","#fd7e14","#ffc107","#6f42c1"],"font":{"color":"#2c3e50","family":"Inter, Segoe UI, Helvetica, sans-serif","size":13},"legend":{"bgcolor":"rgba(255,255,255,0.9)","bordercolor":"#dee2e6","borderwidth":1,"font":{"size":11}},"margin":{"b":50,"l":60,"r":30,"t":60},"paper_bgcolor":"white","plot_bgcolor":"#fafafa","title":{"font":{"color":"#1a1a2e","size":18},"x":0.02,"xanchor":"left"},"xaxis":{"gridcolor":"#e9ecef","linecolor":"#dee2e6","zerolinecolor":"#dee2e6"},"yaxis":{"gridcolor":"#e9ecef","linecolor":"#dee2e6","zerolinecolor":"#dee2e6"}}},"legend":{"orientation":"h","yanchor":"bottom","y":1.02,"xanchor":"right","x":1},"barmode":"stack","title":{"text":"Present Value of Costs by Component ($B)"},"yaxis":{"title":{"text":"PV of Costs ($ Billions)"}},"height":480},                        {"responsive": true}                    ).then(function(){
                            
var gd = document.getElementById('7b7244e0-bd85-4ea6-99b2-98f2b9e9b902');
var x = new MutationObserver(function (mutations, observer) {{
        var display = window.getComputedStyle(gd).display;
        if (!display || display === 'none') {{
            console.log([gd, 'removed!']);
            Plotly.purge(gd);
            observer.disconnect();
        }}
}});

// Listen for the removal of the full notebook cells
var notebookContainer = gd.closest('#notebook-container');
if (notebookContainer) {{
    x.observe(notebookContainer, {childList: true});
}}

// Listen for the clearing of the current output cell
var outputEl = gd.closest('.output');
if (outputEl) {{
    x.observe(outputEl, {childList: true});
}}

                        })                };            </script>        </div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cost-breakdown-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.2: Present value of costs by component for each scenario. Fuel costs dominate BAU; CAPEX dominates alternatives but at lower total cost.
</figcaption>
</figure>
</div>
</div>
<p>The cost structure reveals a fundamental shift between diesel and renewable pathways. Under business-as-usual, the dominant cost component is fuel, which accounts for $14.3 billion or approximately 92 per cent of total lifetime system costs. This reflects the inherent economics of diesel generation: the capital cost of generators is relatively modest, but the ongoing fuel expenditure compounds relentlessly over 30 years, especially as diesel prices escalate and demand grows.</p>
<p>The renewable scenarios invert this cost structure. Capital expenditure — for solar panels, battery systems, and in some cases submarine cables and LNG terminals — becomes the dominant cost component, while fuel costs shrink dramatically or disappear entirely. The critical insight is that even though the upfront CAPEX of the renewable pathways is higher than the BAU generator replacement cost, the total lifetime system cost is substantially lower because the avoided fuel expenditure far outweighs the additional capital investment. Solar panels and batteries, once installed, generate electricity at near-zero marginal cost for decades, whereas diesel generators require a continuous stream of expensive imported fuel.</p>
<p>The Full Integration scenario (S2) is unique in exhibiting significant PPA import costs alongside CAPEX, reflecting the ongoing payments for electricity imported through the India cable. While these import costs are far lower than the diesel fuel costs they displace, they represent a continuing outflow that the purely domestic renewable scenarios avoid entirely.</p>
<section id="sec-fuel-persistence" class="level3" data-number="6.2.1">
<h3 data-number="6.2.1" class="anchored" data-anchor-id="sec-fuel-persistence"><span class="header-section-number">6.2.1</span> Why Fuel Costs Remain Substantial Even Under Renewable Scenarios</h3>
<p>A natural question arises from <a href="#fig-cost-breakdown" class="quarto-xref">Figure&nbsp;<span>6.2</span></a>: if all alternative scenarios involve substantial renewable energy investment, why does fuel still constitute between 26 and 73 per cent of total lifetime costs in the domestic scenarios (S3–S7)? The answer lies in a set of binding physical, geographic, and technical constraints that limit the achievable renewable energy penetration on small coral islands.</p>
<p><strong>Land scarcity.</strong> The most fundamental constraint is that the Maldives has only 134 km² of total inhabited island area, spread across nearly 200 islands. Solar PV requires approximately 7 m² per installed kW (including panel spacing and access), and the model caps the usable share of island area at 15 per cent to preserve land for housing, agriculture, vegetation, and public use. On the smallest and most densely populated islands, solar demand for space exceeds this limit, forcing them into diesel-hybrid configurations regardless of economics. Across all inhabited islands, this physical ceiling means that rooftop and ground-mount solar alone cannot supply the growing national demand.</p>
<p><strong>The Malé bottleneck.</strong> Greater Malé — comprising Malé, Hulhumalé, and Villimalé — consumes more than half of national electricity but is among the most densely built urban areas in the world. With limited available land, rooftop and commercial installations are capped at approximately 34 MWp, which can supply only about 8 per cent of Malé’s demand<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>. Because Malé’s demand share is so large, even if every outer island achieved 100 per cent renewable supply, the national weighted average would be constrained by Malé’s limited rooftop potential. The Near-Shore Solar (S5) and Maximum RE (S6) scenarios exist specifically to break this bottleneck by siting 104 MW on uninhabited islands and 195 MW on floating platforms near Malé — which is why S6 achieves the highest final RE share at 60 per cent.</p>
<p><strong>Deployment speed.</strong> Even where economics and land permit, construction logistics impose a practical ceiling of 80 MW of new solar capacity per year nationally. The ADB Energy Roadmap 2024–2033 identifies a pipeline of 424 MW of planned and potential solar initiatives over five years (approximately 85 MW per year), which the model adopts as the base deployment pace. This reflects the realities of importing equipment to remote atolls, limited port capacity, skilled labour scarcity, and the sequential nature of island-by-island installation. Over the 30 year analysis period, cumulative installations are substantial, but growing demand (at approximately 5 per cent per year) constantly expands the denominator against which the RE share is measured.</p>
<p>Note that the Government of Maldives targets <strong>33 per cent</strong> renewable energy in electricity consumption by 2028 (ADB Energy Roadmap 2024–2033), which requires approximately 800 GWh from renewable sources against projected demand of 2,400 GWh. The model’s deployment trajectory is calibrated to this near-term target, and the scenarios explore what happens as the transition continues beyond 2028 toward 2056, with the ultimate RE share determined by the interplay of deployment speed, land constraints, and demand growth.</p>
<p><strong>Storage duration.</strong> Solar panels produce electricity for roughly six to eight hours per day, concentrated around midday. The model assumes 4 hours of battery storage per site, which covers the evening demand peak but cannot carry load through the entire night. With a maximum depth of discharge of 80 per cent and round-trip efficiency of 88 per cent, the usable energy per cycle is further reduced. Diesel backup therefore remains essential for overnight and extended cloudy-period generation. Increasing storage to eight or more hours would substantially raise RE penetration, but at current battery prices ($350/kWh installed), the cost of doubling storage duration exceeds the fuel savings it would displace.</p>
<p><strong>The net effect</strong> is that even the most ambitious technically feasible scenario (S6 Maximum RE) reaches only 60 per cent renewable penetration by 2056, while the more conservative pathways (S3, S4) plateau around 51 to 51 per cent. The remaining generation gap — ranging from 40 to 5 per cent — must be filled by diesel (or LNG in S7), and the cumulative fuel cost of that residual fossil generation over 30 years is what produces the large red bars visible in every scenario. This persistent fuel exposure is precisely why the sensitivity analysis (<a href="05-sensitivity.html" class="quarto-xref"><span>Chapter 8</span></a>) identifies diesel price as the single most influential parameter across all pathways: even after transition, the Maldives remains partially dependent on imported fuel, and the economic case for transition is strengthened — not weakened — by this reality, because the alternative is <em>total</em> dependence under BAU.</p>
</section>
</section>
<section id="benefit-cost-ratios-and-returns" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="benefit-cost-ratios-and-returns"><span class="header-section-number">6.3</span> Benefit-Cost Ratios and Returns</h2>
<p>The benefit-cost ratio and internal rate of return provide complementary perspectives on the economic attractiveness of each transition pathway. The BCR indicates the total present value of benefits generated per dollar of incremental cost, with any value above 1.0 indicating that the investment creates net value for society. The IRR identifies the discount rate at which the project breaks even, with values exceeding the 6 per cent hurdle rate confirming economic viability.</p>
<div id="cell-fig-bcr-irr" class="cell" data-execution_count="6">
<div id="fig-bcr-irr" class="cell-output cell-output-display quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-bcr-irr-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div>            <script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_SVG"></script><script type="text/javascript">if (window.MathJax && window.MathJax.Hub && window.MathJax.Hub.Config) {window.MathJax.Hub.Config({SVG: {font: "STIX-Web"}});}</script>                <script type="text/javascript">window.PlotlyConfig = {MathJaxConfig: 'local'};</script>
        <script charset="utf-8" src="https://cdn.plot.ly/plotly-3.0.1.min.js" integrity="sha256-oy6Be7Eh6eiQFs5M7oXuPxxm9qbJXEtTpfSI93dW16Q=" crossorigin="anonymous"></script>                <div id="127dbd29-4199-42a0-a11e-11a3e083f70b" class="plotly-graph-div" style="height:400px; width:100%;"></div>            <script type="text/javascript">                window.PLOTLYENV=window.PLOTLYENV || {};                                if (document.getElementById("127dbd29-4199-42a0-a11e-11a3e083f70b")) {                    Plotly.newPlot(                        "127dbd29-4199-42a0-a11e-11a3e083f70b",                        [{"marker":{"color":["#0d6efd","#198754","#0dcaf0","#fd7e14","#ffc107","#6f42c1"]},"showlegend":false,"text":["2.8×","11.2×","7.8×","10.1×","9.1×","10.7×"],"textposition":"outside","x":["S2 FI","S3 NG","S4 IG","S5 NS","S6 MR","S7 LNG"],"y":[2.7793639899101557,11.190657081825014,7.801276113428557,10.105809746242974,9.061532742503086,10.653792087516065],"type":"bar","xaxis":"x","yaxis":"y"},{"marker":{"color":["#0d6efd","#198754","#0dcaf0","#fd7e14","#ffc107","#6f42c1"]},"showlegend":false,"text":["16.1%","32.5%","25.8%","31.9%","31.7%","37.9%"],"textposition":"outside","x":["S2 FI","S3 NG","S4 IG","S5 NS","S6 MR","S7 LNG"],"y":[16.144096571505965,32.4836854590616,25.756579231572196,31.908539224649967,31.68400860908187,37.91048999864315],"type":"bar","xaxis":"x2","yaxis":"y2"}],                        {"template":{"layout":{"colorway":["#6c757d","#0d6efd","#198754","#0dcaf0","#fd7e14","#ffc107","#6f42c1"],"font":{"color":"#2c3e50","family":"Inter, Segoe UI, Helvetica, sans-serif","size":13},"legend":{"bgcolor":"rgba(255,255,255,0.9)","bordercolor":"#dee2e6","borderwidth":1,"font":{"size":11}},"margin":{"b":50,"l":60,"r":30,"t":60},"paper_bgcolor":"white","plot_bgcolor":"#fafafa","title":{"font":{"color":"#1a1a2e","size":18},"x":0.02,"xanchor":"left"},"xaxis":{"gridcolor":"#e9ecef","linecolor":"#dee2e6","zerolinecolor":"#dee2e6"},"yaxis":{"gridcolor":"#e9ecef","linecolor":"#dee2e6","zerolinecolor":"#dee2e6"}}},"xaxis":{"anchor":"y","domain":[0.0,0.45]},"yaxis":{"anchor":"x","domain":[0.0,1.0]},"xaxis2":{"anchor":"y2","domain":[0.55,1.0]},"yaxis2":{"anchor":"x2","domain":[0.0,1.0]},"annotations":[{"font":{"size":16},"showarrow":false,"text":"Benefit-Cost Ratio","x":0.225,"xanchor":"center","xref":"paper","y":1.0,"yanchor":"bottom","yref":"paper"},{"font":{"size":16},"showarrow":false,"text":"Internal Rate of Return (%)","x":0.775,"xanchor":"center","xref":"paper","y":1.0,"yanchor":"bottom","yref":"paper"},{"showarrow":false,"text":"Hurdle rate (6%)","x":1,"xanchor":"right","xref":"x2 domain","y":6.0,"yanchor":"bottom","yref":"y2"}],"shapes":[{"line":{"color":"red","dash":"dash"},"type":"line","x0":0,"x1":1,"xref":"x2 domain","y0":6.0,"y1":6.0,"yref":"y2"}],"height":400},                        {"responsive": true}                    ).then(function(){
                            
var gd = document.getElementById('127dbd29-4199-42a0-a11e-11a3e083f70b');
var x = new MutationObserver(function (mutations, observer) {{
        var display = window.getComputedStyle(gd).display;
        if (!display || display === 'none') {{
            console.log([gd, 'removed!']);
            Plotly.purge(gd);
            observer.disconnect();
        }}
}});

// Listen for the removal of the full notebook cells
var notebookContainer = gd.closest('#notebook-container');
if (notebookContainer) {{
    x.observe(notebookContainer, {childList: true});
}}

// Listen for the clearing of the current output cell
var outputEl = gd.closest('.output');
if (outputEl) {{
    x.observe(outputEl, {childList: true});
}}

                        })                };            </script>        </div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-bcr-irr-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.3: Benefit-cost ratios (left) and internal rates of return (right) for each alternative scenario.
</figcaption>
</figure>
</div>
</div>
<p>The left panel shows that all six alternatives achieve BCRs well above the 1.0 threshold, meaning that society receives substantially more in benefits than it pays in costs under every transition pathway. The right panel shows that the IRR for every scenario exceeds the 6 per cent hurdle rate (indicated by the dashed red line), confirming that the transition investments would generate returns above the social opportunity cost of capital even under more conservative assumptions about the discount rate. The scenarios with the highest BCRs tend to be those that achieve the deepest displacement of diesel fuel, because the avoided fuel costs constitute the largest benefit stream. The LNG scenario (S7) achieves the highest IRR, reflecting its combination of relatively modest CAPEX and rapid, large fuel cost savings from replacing expensive diesel with cheaper gas — even though it does not achieve the highest absolute NPV savings.</p>
<p>The full results table below consolidates all key metrics for ready comparison across scenarios.</p>
<div class="cell" data-execution_count="7">
<div id="tbl-results-summary" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="7">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-results-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6.1: Full scenario comparison table: costs, savings, returns, emissions.
</figcaption>
<div aria-describedby="tbl-results-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="7">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 8%">
<col style="width: 16%">
<col style="width: 11%">
<col style="width: 14%">
<col style="width: 4%">
<col style="width: 7%">
<col style="width: 11%">
<col style="width: 14%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Scenario</th>
<th style="text-align: left;">PV Total Costs (<span class="math inline">\(B)   | LCOE (\)</span>/kWh)</th>
<th style="text-align: left;">NPV Savings ($B)</th>
<th style="text-align: left;">BCR</th>
<th style="text-align: left;">IRR (%)</th>
<th style="text-align: left;">Payback (yr)</th>
<th style="text-align: left;">Emissions (MtCO₂)</th>
<th style="text-align: right;">Final RE (%)</th>
<th style="text-align: left;"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">S1 BAU</td>
<td style="text-align: left;">$15.7</td>
<td style="text-align: left;">$0.437</td>
<td style="text-align: left;">—</td>
<td style="text-align: left;">—</td>
<td style="text-align: left;">—</td>
<td style="text-align: left;">—</td>
<td style="text-align: right;">65.8</td>
<td style="text-align: left;">1%</td>
</tr>
<tr class="even">
<td style="text-align: left;">S2 FI</td>
<td style="text-align: left;">$9.2</td>
<td style="text-align: left;">$0.208</td>
<td style="text-align: left;">$10.0</td>
<td style="text-align: left;">2.8×</td>
<td style="text-align: left;">16.1%</td>
<td style="text-align: left;">13</td>
<td style="text-align: right;">46.2</td>
<td style="text-align: left;">11%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">S3 NG</td>
<td style="text-align: left;">$8.8</td>
<td style="text-align: left;">$0.280</td>
<td style="text-align: left;">$11.0</td>
<td style="text-align: left;">11.2×</td>
<td style="text-align: left;">32.5%</td>
<td style="text-align: left;">7</td>
<td style="text-align: right;">31.9</td>
<td style="text-align: left;">51%</td>
</tr>
<tr class="even">
<td style="text-align: left;">S4 IG</td>
<td style="text-align: left;">$9.8</td>
<td style="text-align: left;">$0.312</td>
<td style="text-align: left;">$9.9</td>
<td style="text-align: left;">7.8×</td>
<td style="text-align: left;">25.8%</td>
<td style="text-align: left;">8</td>
<td style="text-align: right;">32</td>
<td style="text-align: left;">51%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">S5 NS</td>
<td style="text-align: left;">$8.5</td>
<td style="text-align: left;">$0.271</td>
<td style="text-align: left;">$11.6</td>
<td style="text-align: left;">10.1×</td>
<td style="text-align: left;">31.9%</td>
<td style="text-align: left;">8</td>
<td style="text-align: right;">29.4</td>
<td style="text-align: left;">54%</td>
</tr>
<tr class="even">
<td style="text-align: left;">S6 MR</td>
<td style="text-align: left;">$8.0</td>
<td style="text-align: left;">$0.256</td>
<td style="text-align: left;">$12.6</td>
<td style="text-align: left;">9.1×</td>
<td style="text-align: left;">31.7%</td>
<td style="text-align: left;">8</td>
<td style="text-align: right;">25.4</td>
<td style="text-align: left;">60%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">S7 LNG</td>
<td style="text-align: left;">$7.4</td>
<td style="text-align: left;">$0.206</td>
<td style="text-align: left;">$13.0</td>
<td style="text-align: left;">10.7×</td>
<td style="text-align: left;">37.9%</td>
<td style="text-align: left;">7</td>
<td style="text-align: right;">30.6</td>
<td style="text-align: left;">47%</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>The summary table reinforces the central finding that every alternative pathway is economically superior to continued diesel dependence, and it allows the reader to see the trade-offs among them. The scenarios with the highest renewable energy shares tend to deliver the largest NPV savings, the lowest LCOE, and the deepest emissions reductions, but they may also require more capital and involve greater technological risk (as with floating solar in S6). The LNG scenario stands out for its combination of fast payback and high IRR, which reflects its bridging character — it achieves rapid cost savings by swapping one fossil fuel for a cheaper one, rather than by fundamentally transforming the technology base.</p>
</section>
<section id="lcoe-comparison" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="lcoe-comparison"><span class="header-section-number">6.4</span> LCOE Comparison</h2>
<p>The levelised cost of electricity provides the most intuitive metric for comparing generation costs across technologies and scenarios. Unlike total system cost or NPV, which are sensitive to demand projections and discount rates, LCOE expresses the average cost of producing one unit of electricity over the project lifetime, making it directly comparable to retail tariffs, benchmark studies, and international experience.</p>
<div id="cell-fig-lcoe" class="cell" data-execution_count="8">
<div id="fig-lcoe" class="cell-output cell-output-display quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-lcoe-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div>            <script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_SVG"></script><script type="text/javascript">if (window.MathJax && window.MathJax.Hub && window.MathJax.Hub.Config) {window.MathJax.Hub.Config({SVG: {font: "STIX-Web"}});}</script>                <script type="text/javascript">window.PlotlyConfig = {MathJaxConfig: 'local'};</script>
        <script charset="utf-8" src="https://cdn.plot.ly/plotly-3.0.1.min.js" integrity="sha256-oy6Be7Eh6eiQFs5M7oXuPxxm9qbJXEtTpfSI93dW16Q=" crossorigin="anonymous"></script>                <div id="cecccb6f-0c19-4c38-8e6c-9a4f2f2d55e0" class="plotly-graph-div" style="height:450px; width:100%;"></div>            <script type="text/javascript">                window.PLOTLYENV=window.PLOTLYENV || {};                                if (document.getElementById("cecccb6f-0c19-4c38-8e6c-9a4f2f2d55e0")) {                    Plotly.newPlot(                        "cecccb6f-0c19-4c38-8e6c-9a4f2f2d55e0",                        [{"marker":{"color":["#6c757d","#0d6efd","#198754","#0dcaf0","#fd7e14","#ffc107","#6f42c1"]},"name":"Maldives Scenarios","text":["43.7¢","20.8¢","28.0¢","31.2¢","27.1¢","25.6¢","20.6¢"],"textposition":"outside","x":["S1 BAU","S2 FI","S3 NG","S4 IG","S5 NS","S6 MR","S7 LNG"],"y":[43.701155604143175,20.821671011630595,28.049940903673452,31.1717454331058,27.086937280570584,25.574563483328127,20.63287829659005],"type":"bar"}],                        {"template":{"layout":{"colorway":["#6c757d","#0d6efd","#198754","#0dcaf0","#fd7e14","#ffc107","#6f42c1"],"font":{"color":"#2c3e50","family":"Inter, Segoe UI, Helvetica, sans-serif","size":13},"legend":{"bgcolor":"rgba(255,255,255,0.9)","bordercolor":"#dee2e6","borderwidth":1,"font":{"size":11}},"margin":{"b":50,"l":60,"r":30,"t":60},"paper_bgcolor":"white","plot_bgcolor":"#fafafa","title":{"font":{"color":"#1a1a2e","size":18},"x":0.02,"xanchor":"left"},"xaxis":{"gridcolor":"#e9ecef","linecolor":"#dee2e6","zerolinecolor":"#dee2e6"},"yaxis":{"gridcolor":"#e9ecef","linecolor":"#dee2e6","zerolinecolor":"#dee2e6"}}},"shapes":[{"line":{"color":"#27ae60","dash":"dot"},"type":"line","x0":0,"x1":1,"xref":"x domain","y0":4.9,"y1":4.9,"yref":"y"},{"line":{"color":"#f39c12","dash":"dot"},"type":"line","x0":0,"x1":1,"xref":"x domain","y0":16.0,"y1":16.0,"yref":"y"},{"line":{"color":"#e74c3c","dash":"dot"},"type":"line","x0":0,"x1":1,"xref":"x domain","y0":28.000000000000004,"y1":28.000000000000004,"yref":"y"}],"annotations":[{"showarrow":false,"text":"IRENA Global Solar","x":0,"xanchor":"left","xref":"x domain","y":4.9,"yanchor":"bottom","yref":"y"},{"showarrow":false,"text":"SIDS Average RE","x":0,"xanchor":"left","xref":"x domain","y":16.0,"yanchor":"bottom","yref":"y"},{"showarrow":false,"text":"Global Diesel Mini-grid","x":0,"xanchor":"left","xref":"x domain","y":28.000000000000004,"yanchor":"bottom","yref":"y"}],"title":{"text":"Levelised Cost of Electricity (¢\u002fkWh)"},"yaxis":{"title":{"text":"LCOE (¢\u002fkWh)"}},"height":450,"showlegend":false},                        {"responsive": true}                    ).then(function(){
                            
var gd = document.getElementById('cecccb6f-0c19-4c38-8e6c-9a4f2f2d55e0');
var x = new MutationObserver(function (mutations, observer) {{
        var display = window.getComputedStyle(gd).display;
        if (!display || display === 'none') {{
            console.log([gd, 'removed!']);
            Plotly.purge(gd);
            observer.disconnect();
        }}
}});

// Listen for the removal of the full notebook cells
var notebookContainer = gd.closest('#notebook-container');
if (notebookContainer) {{
    x.observe(notebookContainer, {childList: true});
}}

// Listen for the clearing of the current output cell
var outputEl = gd.closest('.output');
if (outputEl) {{
    x.observe(outputEl, {childList: true});
}}

                        })                };            </script>        </div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-lcoe-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.4: Levelised cost of electricity by scenario, with international benchmarks for context.
</figcaption>
</figure>
</div>
</div>
<p>The LCOE comparison chart places the Maldives scenarios in the context of international benchmarks. The diesel BAU LCOE substantially exceeds global diesel mini-grid averages, reflecting the particular cost penalties of small-island generation: fuel transport surcharges, scale inefficiencies of small generators, and high labour costs for maintenance on remote islands. The renewable-based scenarios achieve LCOEs that approach the SIDS average for renewable generation and, in some cases, come close to global utility-scale solar benchmarks — a remarkable achievement for a small island nation with severe logistical constraints. The gap between the BAU LCOE and the best alternative LCOEs represents the per-unit cost advantage of transition, which compounds into the billions of dollars of NPV savings documented above.</p>
</section>
<section id="emissions-trajectories" class="level2" data-number="6.5">
<h2 data-number="6.5" class="anchored" data-anchor-id="emissions-trajectories"><span class="header-section-number">6.5</span> Emissions Trajectories</h2>
<p>Climate impact is a critical dimension of the energy transition decision, both because the Maldives has committed to ambitious emissions reduction targets under the Paris Agreement and because, as the world’s lowest-lying nation, it has an existential stake in global climate action. The figure below compares cumulative CO₂ emissions across all seven scenarios over the 30-year analysis period.</p>
<div id="cell-fig-emissions" class="cell" data-execution_count="9">
<div id="fig-emissions" class="cell-output cell-output-display quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-emissions-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div>            <script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_SVG"></script><script type="text/javascript">if (window.MathJax && window.MathJax.Hub && window.MathJax.Hub.Config) {window.MathJax.Hub.Config({SVG: {font: "STIX-Web"}});}</script>                <script type="text/javascript">window.PlotlyConfig = {MathJaxConfig: 'local'};</script>
        <script charset="utf-8" src="https://cdn.plot.ly/plotly-3.0.1.min.js" integrity="sha256-oy6Be7Eh6eiQFs5M7oXuPxxm9qbJXEtTpfSI93dW16Q=" crossorigin="anonymous"></script>                <div id="3c9b36ad-45c6-4c1a-bbbd-57cca1718cd4" class="plotly-graph-div" style="height:450px; width:100%;"></div>            <script type="text/javascript">                window.PLOTLYENV=window.PLOTLYENV || {};                                if (document.getElementById("3c9b36ad-45c6-4c1a-bbbd-57cca1718cd4")) {                    Plotly.newPlot(                        "3c9b36ad-45c6-4c1a-bbbd-57cca1718cd4",                        [{"marker":{"color":["#b0b0b0","#0d6efd","#198754","#0dcaf0","#fd7e14","#ffc107","#6f42c1"]},"text":["66","46","32","32","29","25","31"],"textposition":"outside","x":["S1 BAU","S2 FI","S3 NG","S4 IG","S5 NS","S6 MR","S7 LNG"],"y":[65.82970902000001,46.20291827180002,31.910132964,32.008447823999994,29.395892375999995,25.365595176,30.567182428],"type":"bar"}],                        {"template":{"layout":{"colorway":["#6c757d","#0d6efd","#198754","#0dcaf0","#fd7e14","#ffc107","#6f42c1"],"font":{"color":"#2c3e50","family":"Inter, Segoe UI, Helvetica, sans-serif","size":13},"legend":{"bgcolor":"rgba(255,255,255,0.9)","bordercolor":"#dee2e6","borderwidth":1,"font":{"size":11}},"margin":{"b":50,"l":60,"r":30,"t":60},"paper_bgcolor":"white","plot_bgcolor":"#fafafa","title":{"font":{"color":"#1a1a2e","size":18},"x":0.02,"xanchor":"left"},"xaxis":{"gridcolor":"#e9ecef","linecolor":"#dee2e6","zerolinecolor":"#dee2e6"},"yaxis":{"gridcolor":"#e9ecef","linecolor":"#dee2e6","zerolinecolor":"#dee2e6"}}},"title":{"text":"Cumulative CO₂ Emissions, 2026–2056 (MtCO₂)"},"yaxis":{"title":{"text":"MtCO₂"}},"xaxis":{"title":{"text":""}},"height":450,"showlegend":false},                        {"responsive": true}                    ).then(function(){
                            
var gd = document.getElementById('3c9b36ad-45c6-4c1a-bbbd-57cca1718cd4');
var x = new MutationObserver(function (mutations, observer) {{
        var display = window.getComputedStyle(gd).display;
        if (!display || display === 'none') {{
            console.log([gd, 'removed!']);
            Plotly.purge(gd);
            observer.disconnect();
        }}
}});

// Listen for the removal of the full notebook cells
var notebookContainer = gd.closest('#notebook-container');
if (notebookContainer) {{
    x.observe(notebookContainer, {childList: true});
}}

// Listen for the clearing of the current output cell
var outputEl = gd.closest('.output');
if (outputEl) {{
    x.observe(outputEl, {childList: true});
}}

                        })                };            </script>        </div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-emissions-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.5: Cumulative CO₂ emissions by scenario. All alternatives achieve significant emission reductions versus diesel BAU.
</figcaption>
</figure>
</div>
</div>
<p>The emissions comparison reveals the enormous environmental dividend of transition. Under diesel BAU, the Maldives electricity sector would emit 65.8 million tonnes of CO₂ over the 30-year period. The cleanest scenario, S6 MR, reduces cumulative emissions by 61 per cent to just 25.4 million tonnes. Even the scenarios that retain some fossil fuel component — such as the LNG Transition (S7), which achieves a 44 per cent reduction in emission intensity by switching from diesel to natural gas — deliver substantial climate benefits relative to the status quo.</p>
<p>The emissions ranking does not perfectly mirror the economic ranking, which creates an interesting policy tension. Some scenarios that are slightly less cost-optimal deliver substantially deeper decarbonisation, meaning that policymakers face a genuine choice about how much additional cost (if any) they are willing to accept to achieve greater emissions reduction. However, the trade-off is modest: the cost difference between the most economically efficient scenario and the most environmentally ambitious one is small relative to the savings both deliver versus diesel.</p>
</section>
<section id="the-india-cable-vs.-domestic-alternatives" class="level2" data-number="6.6">
<h2 data-number="6.6" class="anchored" data-anchor-id="the-india-cable-vs.-domestic-alternatives"><span class="header-section-number">6.6</span> The India Cable vs.&nbsp;Domestic Alternatives</h2>
<p>A question of particular strategic importance is whether the India submarine cable (S2) justifies its substantial cost premium over domestic renewable alternatives. While the cable clearly dominates diesel BAU (as do all alternatives), the relevant policy comparison is against the next-best option that does not require international infrastructure. The incremental analysis comparing S2 (Full Integration) against S3 (National Grid, the best domestic alternative) directly addresses this question.</p>
<p>The incremental analysis reveals that the India cable requires $2.1B in additional capital expenditure beyond what the National Grid domestic scenario would cost. This additional investment yields an incremental benefit-cost ratio of only 0.80, which falls below the 1.0 threshold — meaning that the marginal costs of the cable exceed its marginal benefits relative to domestic solar-plus-battery. The incremental IRR of 1.8 per cent is below the 6 per cent social discount rate, and the incremental payback period extends to 22 years, raising questions about the cable’s economic justification on the margin.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
The cable does not pay for itself on the margin
</div>
</div>
<div class="callout-body-container callout-body">
<p>While S2 saves money versus <em>diesel</em> (BCR 2.8 ×), it does <em>not</em> save money versus <em>domestic solar+battery</em> (S3). The cable’s marginal BCR of 0.80 means that every additional dollar invested in the cable yields only 80 cents of additional benefit. Domestic RE is more cost-effective.</p>
</div>
</div>
<p>This finding does not categorically rule out the India cable — there may be strategic, geopolitical, or energy security arguments that fall outside the scope of economic CBA. However, it does establish that from a pure cost-effectiveness standpoint, the Maldives would be better served by investing the same capital in domestic solar, battery, and near-shore solar capacity. The cable’s marginal economics would improve if India were to share the construction cost (the sensitivity analysis explores a 50 per cent cost-sharing scenario), if Indian electricity export prices were lower than assumed, or if domestic solar deployment encountered unforeseen cost escalation. These conditions are possible but uncertain, which reinforces the real-options argument for deferring the cable decision presented in <a href="C-supplementary.html#sec-real-options" class="quarto-xref"><span>Section 15.4</span></a>.</p>


<!-- -->

</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>ADB Energy Roadmap 2024–2033 (Table 8): 4 MW ASSURE rooftop + 5 MW additional rooftop + 25 MW commercial rooftop on Gulhifalhu/Thilafushi = 34 MWp total. This is nearly double the earlier ZNES Flensburg estimate of 18 MWp (public buildings and sports facilities only).<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./03-scenarios.html" class="pagination-link" aria-label="The Seven Scenarios">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">The Seven Scenarios</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./05-sensitivity.html" class="pagination-link" aria-label="Sensitivity &amp; Robustness">
        <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Sensitivity &amp; Robustness</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb1" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: setup</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> sys</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>sys.path.insert(<span class="dv">0</span>, <span class="st">"."</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> _common <span class="im">import</span> <span class="op">*</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> plotly.graph_objects <span class="im">as</span> go</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> plotly.subplots <span class="im">import</span> make_subplots</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu"># Results {#sec-results}</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>::: {.chapter-opening}</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>This chapter presents the core economic findings of the cost-benefit analysis. It examines the present-value costs, savings, benefit-cost ratios, levelised costs of electricity, and emissions trajectories for all seven scenarios, and provides a detailed incremental analysis comparing the India cable against domestic renewable alternatives.</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="fu">## The Big Picture: All Alternatives Beat Diesel</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>The most important finding of this analysis can be stated simply: every single alternative pathway generates billions of dollars in net economic benefits compared to continued diesel dependence. This result is not marginal or ambiguous — the savings are large, they are consistent across scenarios, and as demonstrated in @sec-sensitivity, they are robust to wide variation in key parameters.</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-npv-savings</span></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Net present value of savings versus BAU for each alternative scenario. All alternatives generate billions in net benefits."</span></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>savings <span class="op">=</span> {s: get_incremental(s)[<span class="st">"npv_savings"</span>] <span class="op">/</span> <span class="fl">1e9</span> <span class="cf">for</span> s <span class="kw">in</span> ALT_SCENARIOS}</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>fig <span class="op">=</span> bar_scenario_comparison(</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>    values<span class="op">=</span>savings,</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>    title<span class="op">=</span><span class="st">"NPV Savings vs. Diesel BAU ($ Billions)"</span>,</span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>    yaxis_title<span class="op">=</span><span class="st">"NPV Savings ($B)"</span>,</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>    highlight_bau<span class="op">=</span><span class="va">False</span>,</span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>fig.update_layout(height<span class="op">=</span><span class="dv">420</span>)</span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>fig.show()</span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: headline-numbers</span></span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a>best_sid <span class="op">=</span> <span class="bu">max</span>(ALT_SCENARIOS, key<span class="op">=</span><span class="kw">lambda</span> s: get_incremental(s)[<span class="st">"npv_savings"</span>])</span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a>worst_sid <span class="op">=</span> <span class="bu">min</span>(ALT_SCENARIOS, key<span class="op">=</span><span class="kw">lambda</span> s: get_incremental(s)[<span class="st">"npv_savings"</span>])</span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a>best_savings <span class="op">=</span> get_incremental(best_sid)[<span class="st">"npv_savings"</span>] <span class="op">/</span> <span class="fl">1e9</span></span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a>worst_savings <span class="op">=</span> get_incremental(worst_sid)[<span class="st">"npv_savings"</span>] <span class="op">/</span> <span class="fl">1e9</span></span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a>The figure above displays the net present value of savings for each alternative scenario relative to the diesel business-as-usual counterfactual. The results are unambiguous: every alternative saves the Maldives between <span class="in">`{python} f"${worst_savings:,.1f}"`</span> billion and <span class="in">`{python} f"${best_savings:,.1f}"`</span> billion in present value over the <span class="in">`{python} f"{cba['end_year'] - cba['base_year']}"`</span>-year analysis period. The <span class="in">`{python} SCENARIO_LABELS[best_sid]`</span> scenario achieves the highest NPV savings, while even <span class="in">`{python} SCENARIO_LABELS[worst_sid]`</span> — the least advantageous alternative — delivers substantial net benefits. The magnitude of these savings reflects the enormous cumulative cost of diesel fuel over three decades, which dwarfs the upfront capital investment required for any of the transition pathways.</span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a>It is worth emphasising that these savings are calculated at a <span class="in">`{python} f"{cba['discount_rate']*100:.0f}"`</span> per cent real discount rate, which heavily discounts benefits occurring in later years. At lower discount rates (<span class="in">`{python} f"{param('Discount Rate', 'Low')*100:.0f}"`</span>–4 per cent, as used by several OECD development agencies), the savings would be even larger, because the long tail of fuel cost avoidance in the 2040s and 2050s receives greater weight. Conversely, even at the high end of the ADB range (<span class="in">`{python} f"{param('Discount Rate', 'High')*100:.0f}"`</span> per cent), all alternatives still dominate diesel — the breakeven discount rate for every scenario is well above <span class="in">`{python} f"{irr_min:.0f}"`</span> per cent.</span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a><span class="fu">## Cost Breakdown by Component</span></span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a>Understanding *why* the alternatives are cheaper requires examining the composition of costs under each pathway. The stacked bar chart below decomposes the present value of total system costs into four components: capital expenditure (the upfront investment in solar panels, batteries, cables, generators, and other infrastructure), operating expenditure (annual maintenance, labour, and non-fuel running costs), fuel costs (diesel and LNG purchases), and power purchase agreement imports (the cost of electricity imported via the India cable).</span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-58"><a href="#cb1-58" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb1-59"><a href="#cb1-59" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-cost-breakdown</span></span>
<span id="cb1-60"><a href="#cb1-60" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Present value of costs by component for each scenario. Fuel costs dominate BAU; CAPEX dominates alternatives but at lower total cost."</span></span>
<span id="cb1-61"><a href="#cb1-61" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-62"><a href="#cb1-62" aria-hidden="true" tabindex="-1"></a>components <span class="op">=</span> [<span class="st">"pv_capex"</span>, <span class="st">"pv_opex"</span>, <span class="st">"pv_fuel"</span>, <span class="st">"pv_ppa"</span>]</span>
<span id="cb1-63"><a href="#cb1-63" aria-hidden="true" tabindex="-1"></a>comp_labels <span class="op">=</span> [<span class="st">"CAPEX"</span>, <span class="st">"OPEX"</span>, <span class="st">"Fuel"</span>, <span class="st">"PPA Imports"</span>]</span>
<span id="cb1-64"><a href="#cb1-64" aria-hidden="true" tabindex="-1"></a>comp_colors <span class="op">=</span> [<span class="st">"#3498db"</span>, <span class="st">"#2ecc71"</span>, <span class="st">"#e74c3c"</span>, <span class="st">"#9b59b6"</span>]</span>
<span id="cb1-65"><a href="#cb1-65" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-66"><a href="#cb1-66" aria-hidden="true" tabindex="-1"></a>fig <span class="op">=</span> go.Figure()</span>
<span id="cb1-67"><a href="#cb1-67" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> comp, label, color <span class="kw">in</span> <span class="bu">zip</span>(components, comp_labels, comp_colors):</span>
<span id="cb1-68"><a href="#cb1-68" aria-hidden="true" tabindex="-1"></a>    vals <span class="op">=</span> [cba[<span class="st">"npv_results"</span>][s].get(comp, <span class="dv">0</span>) <span class="op">/</span> <span class="fl">1e9</span> <span class="cf">for</span> s <span class="kw">in</span> SCENARIO_IDS]</span>
<span id="cb1-69"><a href="#cb1-69" aria-hidden="true" tabindex="-1"></a>    fig.add_trace(go.Bar(</span>
<span id="cb1-70"><a href="#cb1-70" aria-hidden="true" tabindex="-1"></a>        name<span class="op">=</span>label,</span>
<span id="cb1-71"><a href="#cb1-71" aria-hidden="true" tabindex="-1"></a>        x<span class="op">=</span>[SCENARIO_SHORT[s] <span class="cf">for</span> s <span class="kw">in</span> SCENARIO_IDS],</span>
<span id="cb1-72"><a href="#cb1-72" aria-hidden="true" tabindex="-1"></a>        y<span class="op">=</span>vals,</span>
<span id="cb1-73"><a href="#cb1-73" aria-hidden="true" tabindex="-1"></a>        marker_color<span class="op">=</span>color,</span>
<span id="cb1-74"><a href="#cb1-74" aria-hidden="true" tabindex="-1"></a>    ))</span>
<span id="cb1-75"><a href="#cb1-75" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-76"><a href="#cb1-76" aria-hidden="true" tabindex="-1"></a>fig.update_layout(</span>
<span id="cb1-77"><a href="#cb1-77" aria-hidden="true" tabindex="-1"></a>    barmode<span class="op">=</span><span class="st">"stack"</span>,</span>
<span id="cb1-78"><a href="#cb1-78" aria-hidden="true" tabindex="-1"></a>    title<span class="op">=</span><span class="st">"Present Value of Costs by Component ($B)"</span>,</span>
<span id="cb1-79"><a href="#cb1-79" aria-hidden="true" tabindex="-1"></a>    yaxis_title<span class="op">=</span><span class="st">"PV of Costs ($ Billions)"</span>,</span>
<span id="cb1-80"><a href="#cb1-80" aria-hidden="true" tabindex="-1"></a>    height<span class="op">=</span><span class="dv">480</span>,</span>
<span id="cb1-81"><a href="#cb1-81" aria-hidden="true" tabindex="-1"></a>    legend<span class="op">=</span><span class="bu">dict</span>(orientation<span class="op">=</span><span class="st">"h"</span>, yanchor<span class="op">=</span><span class="st">"bottom"</span>, y<span class="op">=</span><span class="fl">1.02</span>, xanchor<span class="op">=</span><span class="st">"right"</span>, x<span class="op">=</span><span class="dv">1</span>),</span>
<span id="cb1-82"><a href="#cb1-82" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-83"><a href="#cb1-83" aria-hidden="true" tabindex="-1"></a>fig.show()</span>
<span id="cb1-84"><a href="#cb1-84" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-85"><a href="#cb1-85" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-86"><a href="#cb1-86" aria-hidden="true" tabindex="-1"></a>The cost structure reveals a fundamental shift between diesel and renewable pathways. Under business-as-usual, the dominant cost component is fuel, which accounts for <span class="in">`{python} f"${cba['npv_results']['bau']['pv_fuel']/1e9:,.1f}"`</span> billion or approximately <span class="in">`{python} f"{cba['npv_results']['bau']['pv_fuel']/cba['npv_results']['bau']['pv_total_costs']*100:.0f}"`</span> per cent of total lifetime system costs. This reflects the inherent economics of diesel generation: the capital cost of generators is relatively modest, but the ongoing fuel expenditure compounds relentlessly over <span class="in">`{python} f"{cba['end_year'] - cba['base_year']}"`</span> years, especially as diesel prices escalate and demand grows.</span>
<span id="cb1-87"><a href="#cb1-87" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-88"><a href="#cb1-88" aria-hidden="true" tabindex="-1"></a>The renewable scenarios invert this cost structure. Capital expenditure — for solar panels, battery systems, and in some cases submarine cables and LNG terminals — becomes the dominant cost component, while fuel costs shrink dramatically or disappear entirely. The critical insight is that even though the upfront CAPEX of the renewable pathways is higher than the BAU generator replacement cost, the total lifetime system cost is substantially lower because the avoided fuel expenditure far outweighs the additional capital investment. Solar panels and batteries, once installed, generate electricity at near-zero marginal cost for decades, whereas diesel generators require a continuous stream of expensive imported fuel.</span>
<span id="cb1-89"><a href="#cb1-89" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-90"><a href="#cb1-90" aria-hidden="true" tabindex="-1"></a>The Full Integration scenario (S2) is unique in exhibiting significant PPA import costs alongside CAPEX, reflecting the ongoing payments for electricity imported through the India cable. While these import costs are far lower than the diesel fuel costs they displace, they represent a continuing outflow that the purely domestic renewable scenarios avoid entirely.</span>
<span id="cb1-91"><a href="#cb1-91" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-92"><a href="#cb1-92" aria-hidden="true" tabindex="-1"></a><span class="fu">### Why Fuel Costs Remain Substantial Even Under Renewable Scenarios {#sec-fuel-persistence}</span></span>
<span id="cb1-93"><a href="#cb1-93" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-96"><a href="#cb1-96" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb1-97"><a href="#cb1-97" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fuel-persistence-data</span></span>
<span id="cb1-98"><a href="#cb1-98" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-99"><a href="#cb1-99" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute fuel shares and RE shares for all scenarios</span></span>
<span id="cb1-100"><a href="#cb1-100" aria-hidden="true" tabindex="-1"></a>_fuel_pcts <span class="op">=</span> {}</span>
<span id="cb1-101"><a href="#cb1-101" aria-hidden="true" tabindex="-1"></a>_re_finals <span class="op">=</span> {}</span>
<span id="cb1-102"><a href="#cb1-102" aria-hidden="true" tabindex="-1"></a>_diesel_shares <span class="op">=</span> {}</span>
<span id="cb1-103"><a href="#cb1-103" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> _s <span class="kw">in</span> SCENARIO_IDS:</span>
<span id="cb1-104"><a href="#cb1-104" aria-hidden="true" tabindex="-1"></a>    _nr <span class="op">=</span> cba[<span class="st">"npv_results"</span>][_s]</span>
<span id="cb1-105"><a href="#cb1-105" aria-hidden="true" tabindex="-1"></a>    _fuel_pcts[_s] <span class="op">=</span> _nr.get(<span class="st">"pv_fuel"</span>, <span class="dv">0</span>) <span class="op">/</span> _nr[<span class="st">"pv_total_costs"</span>] <span class="op">*</span> <span class="dv">100</span></span>
<span id="cb1-106"><a href="#cb1-106" aria-hidden="true" tabindex="-1"></a>    _ss_data <span class="op">=</span> summaries[_s]</span>
<span id="cb1-107"><a href="#cb1-107" aria-hidden="true" tabindex="-1"></a>    _re_finals[_s] <span class="op">=</span> _ss_data[<span class="st">"final_re_share"</span>] <span class="op">*</span> <span class="dv">100</span></span>
<span id="cb1-108"><a href="#cb1-108" aria-hidden="true" tabindex="-1"></a>    _diesel_shares[_s] <span class="op">=</span> _ss_data.get(<span class="st">"final_diesel_share"</span>, <span class="fl">1.0</span> <span class="op">-</span> _ss_data[<span class="st">"final_re_share"</span>]) <span class="op">*</span> <span class="dv">100</span></span>
<span id="cb1-109"><a href="#cb1-109" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-110"><a href="#cb1-110" aria-hidden="true" tabindex="-1"></a>_best_re_sid <span class="op">=</span> <span class="bu">max</span>(ALT_SCENARIOS, key<span class="op">=</span><span class="kw">lambda</span> s: _re_finals[s])</span>
<span id="cb1-111"><a href="#cb1-111" aria-hidden="true" tabindex="-1"></a>_best_re_pct <span class="op">=</span> _re_finals[_best_re_sid]</span>
<span id="cb1-112"><a href="#cb1-112" aria-hidden="true" tabindex="-1"></a>_worst_re_sid <span class="op">=</span> <span class="bu">min</span>(ALT_SCENARIOS, key<span class="op">=</span><span class="kw">lambda</span> s: _re_finals[s])</span>
<span id="cb1-113"><a href="#cb1-113" aria-hidden="true" tabindex="-1"></a>_worst_re_pct <span class="op">=</span> _re_finals[_worst_re_sid]</span>
<span id="cb1-114"><a href="#cb1-114" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-115"><a href="#cb1-115" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-116"><a href="#cb1-116" aria-hidden="true" tabindex="-1"></a>A natural question arises from @fig-cost-breakdown: if all alternative scenarios involve substantial renewable energy investment, why does fuel still constitute between <span class="in">`{python} f"{min(_fuel_pcts[s] for s in ALT_SCENARIOS):.0f}"`</span> and <span class="in">`{python} f"{max(_fuel_pcts[s] for s in ALT_SCENARIOS):.0f}"`</span> per cent of total lifetime costs in the domestic scenarios (S3–S7)? The answer lies in a set of binding physical, geographic, and technical constraints that limit the achievable renewable energy penetration on small coral islands.</span>
<span id="cb1-117"><a href="#cb1-117" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-118"><a href="#cb1-118" aria-hidden="true" tabindex="-1"></a>**Land scarcity.** The most fundamental constraint is that the Maldives has only <span class="in">`{python} f"{param('Total Inhabited Island Area'):.0f}"`</span> km² of total inhabited island area, spread across nearly 200 islands. Solar PV requires approximately <span class="in">`{python} f"{param('Area Per kW'):.0f}"`</span> m² per installed kW (including panel spacing and access), and the model caps the usable share of island area at <span class="in">`{python} f"{param('Max Land Fraction')*100:.0f}"`</span> per cent to preserve land for housing, agriculture, vegetation, and public use. On the smallest and most densely populated islands, solar demand for space exceeds this limit, forcing them into diesel-hybrid configurations regardless of economics. Across all inhabited islands, this physical ceiling means that rooftop and ground-mount solar alone cannot supply the growing national demand.</span>
<span id="cb1-119"><a href="#cb1-119" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-120"><a href="#cb1-120" aria-hidden="true" tabindex="-1"></a>**The Malé bottleneck.** Greater Malé — comprising Malé, Hulhumalé, and Villimalé — consumes more than half of national electricity but is among the most densely built urban areas in the world. With limited available land, rooftop and commercial installations are capped at approximately <span class="in">`{python} f"{param('Male Rooftop Solar Potential'):.0f}"`</span> MWp, which can supply only about <span class="in">`{python} f"{param('Male Max RE Share')*100:.0f}"`</span> per cent of Malé's demand^<span class="co">[</span><span class="ot">ADB Energy Roadmap 2024–2033 (Table 8): 4 MW ASSURE rooftop + 5 MW additional rooftop + 25 MW commercial rooftop on Gulhifalhu/Thilafushi = 34 MWp total. This is nearly double the earlier ZNES Flensburg estimate of 18 MWp (public buildings and sports facilities only).</span><span class="co">]</span>. Because Malé's demand share is so large, even if every outer island achieved 100 per cent renewable supply, the national weighted average would be constrained by Malé's limited rooftop potential. The Near-Shore Solar (S5) and Maximum RE (S6) scenarios exist specifically to break this bottleneck by siting <span class="in">`{python} f"{param('Near-Shore Solar MW'):.0f}"`</span> MW on uninhabited islands and <span class="in">`{python} f"{param('Floating Solar MW'):.0f}"`</span> MW on floating platforms near Malé — which is why S6 achieves the highest final RE share at <span class="in">`{python} f"{_best_re_pct:.0f}"`</span> per cent.</span>
<span id="cb1-121"><a href="#cb1-121" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-122"><a href="#cb1-122" aria-hidden="true" tabindex="-1"></a>**Deployment speed.** Even where economics and land permit, construction logistics impose a practical ceiling of <span class="in">`{python} f"{param('Deployment Ramp MW per Year'):.0f}"`</span> MW of new solar capacity per year nationally. The ADB Energy Roadmap 2024–2033 identifies a pipeline of 424 MW of planned and potential solar initiatives over five years (approximately 85 MW per year), which the model adopts as the base deployment pace. This reflects the realities of importing equipment to remote atolls, limited port capacity, skilled labour scarcity, and the sequential nature of island-by-island installation. Over the <span class="in">`{python} f"{cba['end_year'] - cba['base_year']}"`</span> year analysis period, cumulative installations are substantial, but growing demand (at approximately <span class="in">`{python} f"{param('Growth Rate - BAU')*100:.0f}"`</span> per cent per year) constantly expands the denominator against which the RE share is measured.</span>
<span id="cb1-123"><a href="#cb1-123" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-124"><a href="#cb1-124" aria-hidden="true" tabindex="-1"></a>Note that the Government of Maldives targets **33 per cent** renewable energy in electricity consumption by 2028 (ADB Energy Roadmap 2024–2033), which requires approximately 800 GWh from renewable sources against projected demand of 2,400 GWh. The model's deployment trajectory is calibrated to this near-term target, and the scenarios explore what happens as the transition continues beyond 2028 toward 2056, with the ultimate RE share determined by the interplay of deployment speed, land constraints, and demand growth.</span>
<span id="cb1-125"><a href="#cb1-125" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-126"><a href="#cb1-126" aria-hidden="true" tabindex="-1"></a>**Storage duration.** Solar panels produce electricity for roughly six to eight hours per day, concentrated around midday. The model assumes <span class="in">`{python} f"{param('Storage Hours'):.0f}"`</span> hours of battery storage per site, which covers the evening demand peak but cannot carry load through the entire night. With a maximum depth of discharge of <span class="in">`{python} f"{param('Battery DoD Max')*100:.0f}"`</span> per cent and round-trip efficiency of <span class="in">`{python} f"{param('Round-trip Efficiency')*100:.0f}"`</span> per cent, the usable energy per cycle is further reduced. Diesel backup therefore remains essential for overnight and extended cloudy-period generation. Increasing storage to eight or more hours would substantially raise RE penetration, but at current battery prices (<span class="in">`{python} f"${param('CAPEX 2026', category='Battery'):.0f}"`</span>/kWh installed), the cost of doubling storage duration exceeds the fuel savings it would displace.</span>
<span id="cb1-127"><a href="#cb1-127" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-128"><a href="#cb1-128" aria-hidden="true" tabindex="-1"></a>**The net effect** is that even the most ambitious technically feasible scenario (S6 Maximum RE) reaches only <span class="in">`{python} f"{_best_re_pct:.0f}"`</span> per cent renewable penetration by <span class="in">`{python} f"{cba['end_year']}"`</span>, while the more conservative pathways (S3, S4) plateau around <span class="in">`{python} f"{_re_finals['national_grid']:.0f}"`</span> to <span class="in">`{python} f"{_re_finals['islanded_green']:.0f}"`</span> per cent. The remaining generation gap — ranging from <span class="in">`{python} f"{_diesel_shares[_best_re_sid]:.0f}"`</span> to <span class="in">`{python} f"{_diesel_shares[_worst_re_sid]:.0f}"`</span> per cent — must be filled by diesel (or LNG in S7), and the cumulative fuel cost of that residual fossil generation over <span class="in">`{python} f"{cba['end_year'] - cba['base_year']}"`</span> years is what produces the large red bars visible in every scenario. This persistent fuel exposure is precisely why the sensitivity analysis (@sec-sensitivity) identifies diesel price as the single most influential parameter across all pathways: even after transition, the Maldives remains partially dependent on imported fuel, and the economic case for transition is strengthened — not weakened — by this reality, because the alternative is *total* dependence under BAU.</span>
<span id="cb1-129"><a href="#cb1-129" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-130"><a href="#cb1-130" aria-hidden="true" tabindex="-1"></a><span class="fu">## Benefit-Cost Ratios and Returns</span></span>
<span id="cb1-131"><a href="#cb1-131" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-132"><a href="#cb1-132" aria-hidden="true" tabindex="-1"></a>The benefit-cost ratio and internal rate of return provide complementary perspectives on the economic attractiveness of each transition pathway. The BCR indicates the total present value of benefits generated per dollar of incremental cost, with any value above 1.0 indicating that the investment creates net value for society. The IRR identifies the discount rate at which the project breaks even, with values exceeding the <span class="in">`{python} f"{cba['discount_rate']*100:.0f}"`</span> per cent hurdle rate confirming economic viability.</span>
<span id="cb1-133"><a href="#cb1-133" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-136"><a href="#cb1-136" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb1-137"><a href="#cb1-137" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-bcr-irr</span></span>
<span id="cb1-138"><a href="#cb1-138" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Benefit-cost ratios (left) and internal rates of return (right) for each alternative scenario."</span></span>
<span id="cb1-139"><a href="#cb1-139" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-140"><a href="#cb1-140" aria-hidden="true" tabindex="-1"></a>fig <span class="op">=</span> make_subplots(rows<span class="op">=</span><span class="dv">1</span>, cols<span class="op">=</span><span class="dv">2</span>, subplot_titles<span class="op">=</span>[<span class="st">"Benefit-Cost Ratio"</span>, <span class="st">"Internal Rate of Return (%)"</span>])</span>
<span id="cb1-141"><a href="#cb1-141" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-142"><a href="#cb1-142" aria-hidden="true" tabindex="-1"></a>bcrs <span class="op">=</span> {s: get_incremental(s)[<span class="st">"bcr"</span>] <span class="cf">for</span> s <span class="kw">in</span> ALT_SCENARIOS}</span>
<span id="cb1-143"><a href="#cb1-143" aria-hidden="true" tabindex="-1"></a>irrs <span class="op">=</span> {s: get_incremental(s)[<span class="st">"irr"</span>] <span class="op">*</span> <span class="dv">100</span> <span class="cf">for</span> s <span class="kw">in</span> ALT_SCENARIOS}</span>
<span id="cb1-144"><a href="#cb1-144" aria-hidden="true" tabindex="-1"></a>labels <span class="op">=</span> [SCENARIO_SHORT[s] <span class="cf">for</span> s <span class="kw">in</span> ALT_SCENARIOS]</span>
<span id="cb1-145"><a href="#cb1-145" aria-hidden="true" tabindex="-1"></a>colors <span class="op">=</span> [SCENARIO_COLORS[s] <span class="cf">for</span> s <span class="kw">in</span> ALT_SCENARIOS]</span>
<span id="cb1-146"><a href="#cb1-146" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-147"><a href="#cb1-147" aria-hidden="true" tabindex="-1"></a>fig.add_trace(go.Bar(</span>
<span id="cb1-148"><a href="#cb1-148" aria-hidden="true" tabindex="-1"></a>    x<span class="op">=</span>labels, y<span class="op">=</span><span class="bu">list</span>(bcrs.values()),</span>
<span id="cb1-149"><a href="#cb1-149" aria-hidden="true" tabindex="-1"></a>    marker_color<span class="op">=</span>colors,</span>
<span id="cb1-150"><a href="#cb1-150" aria-hidden="true" tabindex="-1"></a>    text<span class="op">=</span>[<span class="ss">f"</span><span class="sc">{</span>v<span class="sc">:.1f}</span><span class="ss">×"</span> <span class="cf">for</span> v <span class="kw">in</span> bcrs.values()],</span>
<span id="cb1-151"><a href="#cb1-151" aria-hidden="true" tabindex="-1"></a>    textposition<span class="op">=</span><span class="st">"outside"</span>,</span>
<span id="cb1-152"><a href="#cb1-152" aria-hidden="true" tabindex="-1"></a>    showlegend<span class="op">=</span><span class="va">False</span>,</span>
<span id="cb1-153"><a href="#cb1-153" aria-hidden="true" tabindex="-1"></a>), row<span class="op">=</span><span class="dv">1</span>, col<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb1-154"><a href="#cb1-154" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-155"><a href="#cb1-155" aria-hidden="true" tabindex="-1"></a>fig.add_trace(go.Bar(</span>
<span id="cb1-156"><a href="#cb1-156" aria-hidden="true" tabindex="-1"></a>    x<span class="op">=</span>labels, y<span class="op">=</span><span class="bu">list</span>(irrs.values()),</span>
<span id="cb1-157"><a href="#cb1-157" aria-hidden="true" tabindex="-1"></a>    marker_color<span class="op">=</span>colors,</span>
<span id="cb1-158"><a href="#cb1-158" aria-hidden="true" tabindex="-1"></a>    text<span class="op">=</span>[<span class="ss">f"</span><span class="sc">{</span>v<span class="sc">:.1f}</span><span class="ss">%"</span> <span class="cf">for</span> v <span class="kw">in</span> irrs.values()],</span>
<span id="cb1-159"><a href="#cb1-159" aria-hidden="true" tabindex="-1"></a>    textposition<span class="op">=</span><span class="st">"outside"</span>,</span>
<span id="cb1-160"><a href="#cb1-160" aria-hidden="true" tabindex="-1"></a>    showlegend<span class="op">=</span><span class="va">False</span>,</span>
<span id="cb1-161"><a href="#cb1-161" aria-hidden="true" tabindex="-1"></a>), row<span class="op">=</span><span class="dv">1</span>, col<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb1-162"><a href="#cb1-162" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-163"><a href="#cb1-163" aria-hidden="true" tabindex="-1"></a><span class="co"># Add hurdle rate line</span></span>
<span id="cb1-164"><a href="#cb1-164" aria-hidden="true" tabindex="-1"></a>fig.add_hline(y<span class="op">=</span>cba[<span class="st">"discount_rate"</span>] <span class="op">*</span> <span class="dv">100</span>, line_dash<span class="op">=</span><span class="st">"dash"</span>, line_color<span class="op">=</span><span class="st">"red"</span>,</span>
<span id="cb1-165"><a href="#cb1-165" aria-hidden="true" tabindex="-1"></a>              annotation_text<span class="op">=</span><span class="ss">f"Hurdle rate (</span><span class="sc">{</span>cba[<span class="st">'discount_rate'</span>]<span class="op">*</span><span class="dv">100</span><span class="sc">:.0f}</span><span class="ss">%)"</span>,</span>
<span id="cb1-166"><a href="#cb1-166" aria-hidden="true" tabindex="-1"></a>              row<span class="op">=</span><span class="dv">1</span>, col<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb1-167"><a href="#cb1-167" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-168"><a href="#cb1-168" aria-hidden="true" tabindex="-1"></a>fig.update_layout(height<span class="op">=</span><span class="dv">400</span>)</span>
<span id="cb1-169"><a href="#cb1-169" aria-hidden="true" tabindex="-1"></a>fig.show()</span>
<span id="cb1-170"><a href="#cb1-170" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-171"><a href="#cb1-171" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-172"><a href="#cb1-172" aria-hidden="true" tabindex="-1"></a>The left panel shows that all six alternatives achieve BCRs well above the 1.0 threshold, meaning that society receives substantially more in benefits than it pays in costs under every transition pathway. The right panel shows that the IRR for every scenario exceeds the <span class="in">`{python} f"{cba['discount_rate']*100:.0f}"`</span> per cent hurdle rate (indicated by the dashed red line), confirming that the transition investments would generate returns above the social opportunity cost of capital even under more conservative assumptions about the discount rate. The scenarios with the highest BCRs tend to be those that achieve the deepest displacement of diesel fuel, because the avoided fuel costs constitute the largest benefit stream. The LNG scenario (S7) achieves the highest IRR, reflecting its combination of relatively modest CAPEX and rapid, large fuel cost savings from replacing expensive diesel with cheaper gas — even though it does not achieve the highest absolute NPV savings.</span>
<span id="cb1-173"><a href="#cb1-173" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-174"><a href="#cb1-174" aria-hidden="true" tabindex="-1"></a>The full results table below consolidates all key metrics for ready comparison across scenarios.</span>
<span id="cb1-175"><a href="#cb1-175" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-178"><a href="#cb1-178" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb1-179"><a href="#cb1-179" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tbl-results-summary</span></span>
<span id="cb1-180"><a href="#cb1-180" aria-hidden="true" tabindex="-1"></a><span class="co">#| tbl-cap: "Full scenario comparison table: costs, savings, returns, emissions."</span></span>
<span id="cb1-181"><a href="#cb1-181" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-182"><a href="#cb1-182" aria-hidden="true" tabindex="-1"></a>tbl <span class="op">=</span> make_summary_table()</span>
<span id="cb1-183"><a href="#cb1-183" aria-hidden="true" tabindex="-1"></a>tbl_fmt <span class="op">=</span> tbl.copy()</span>
<span id="cb1-184"><a href="#cb1-184" aria-hidden="true" tabindex="-1"></a>tbl_fmt[<span class="st">"PV Total Costs ($B)"</span>] <span class="op">=</span> tbl_fmt[<span class="st">"PV Total Costs ($B)"</span>].<span class="bu">apply</span>(<span class="kw">lambda</span> x: <span class="ss">f"$</span><span class="sc">{</span>x<span class="sc">:,.1f}</span><span class="ss">"</span>)</span>
<span id="cb1-185"><a href="#cb1-185" aria-hidden="true" tabindex="-1"></a>tbl_fmt[<span class="st">"LCOE ($/kWh)"</span>] <span class="op">=</span> tbl_fmt[<span class="st">"LCOE ($/kWh)"</span>].<span class="bu">apply</span>(<span class="kw">lambda</span> x: <span class="ss">f"$</span><span class="sc">{</span>x<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb1-186"><a href="#cb1-186" aria-hidden="true" tabindex="-1"></a>tbl_fmt[<span class="st">"NPV Savings ($B)"</span>] <span class="op">=</span> tbl_fmt[<span class="st">"NPV Savings ($B)"</span>].<span class="bu">apply</span>(<span class="kw">lambda</span> x: <span class="ss">f"$</span><span class="sc">{</span>x<span class="sc">:,.1f}</span><span class="ss">"</span> <span class="cf">if</span> x <span class="op">&gt;</span> <span class="dv">0</span> <span class="cf">else</span> <span class="st">"—"</span>)</span>
<span id="cb1-187"><a href="#cb1-187" aria-hidden="true" tabindex="-1"></a>tbl_fmt[<span class="st">"BCR"</span>] <span class="op">=</span> tbl_fmt[<span class="st">"BCR"</span>].<span class="bu">apply</span>(<span class="kw">lambda</span> x: <span class="ss">f"</span><span class="sc">{</span>x<span class="sc">:.1f}</span><span class="ss">×"</span> <span class="cf">if</span> <span class="bu">isinstance</span>(x, <span class="bu">float</span>) <span class="cf">else</span> <span class="st">"—"</span>)</span>
<span id="cb1-188"><a href="#cb1-188" aria-hidden="true" tabindex="-1"></a>tbl_fmt[<span class="st">"IRR (%)"</span>] <span class="op">=</span> tbl_fmt[<span class="st">"IRR (%)"</span>].<span class="bu">apply</span>(<span class="kw">lambda</span> x: <span class="ss">f"</span><span class="sc">{</span>x<span class="sc">:.1f}</span><span class="ss">%"</span> <span class="cf">if</span> <span class="bu">isinstance</span>(x, (<span class="bu">int</span>, <span class="bu">float</span>)) <span class="kw">and</span> x <span class="op">&gt;</span> <span class="dv">0</span> <span class="cf">else</span> <span class="st">"—"</span>)</span>
<span id="cb1-189"><a href="#cb1-189" aria-hidden="true" tabindex="-1"></a>tbl_fmt[<span class="st">"Emissions (MtCO₂)"</span>] <span class="op">=</span> tbl_fmt[<span class="st">"Emissions (MtCO₂)"</span>].<span class="bu">apply</span>(<span class="kw">lambda</span> x: <span class="ss">f"</span><span class="sc">{</span>x<span class="sc">:.1f}</span><span class="ss">"</span>)</span>
<span id="cb1-190"><a href="#cb1-190" aria-hidden="true" tabindex="-1"></a>tbl_fmt[<span class="st">"Final RE (%)"</span>] <span class="op">=</span> tbl_fmt[<span class="st">"Final RE (%)"</span>].<span class="bu">apply</span>(<span class="kw">lambda</span> x: <span class="ss">f"</span><span class="sc">{</span>x<span class="sc">:.0f}</span><span class="ss">%"</span>)</span>
<span id="cb1-191"><a href="#cb1-191" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-192"><a href="#cb1-192" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> IPython.display <span class="im">import</span> Markdown</span>
<span id="cb1-193"><a href="#cb1-193" aria-hidden="true" tabindex="-1"></a>Markdown(tbl_fmt.to_markdown(index<span class="op">=</span><span class="va">False</span>))</span>
<span id="cb1-194"><a href="#cb1-194" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-195"><a href="#cb1-195" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-196"><a href="#cb1-196" aria-hidden="true" tabindex="-1"></a>The summary table reinforces the central finding that every alternative pathway is economically superior to continued diesel dependence, and it allows the reader to see the trade-offs among them. The scenarios with the highest renewable energy shares tend to deliver the largest NPV savings, the lowest LCOE, and the deepest emissions reductions, but they may also require more capital and involve greater technological risk (as with floating solar in S6). The LNG scenario stands out for its combination of fast payback and high IRR, which reflects its bridging character — it achieves rapid cost savings by swapping one fossil fuel for a cheaper one, rather than by fundamentally transforming the technology base.</span>
<span id="cb1-197"><a href="#cb1-197" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-198"><a href="#cb1-198" aria-hidden="true" tabindex="-1"></a><span class="fu">## LCOE Comparison</span></span>
<span id="cb1-199"><a href="#cb1-199" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-200"><a href="#cb1-200" aria-hidden="true" tabindex="-1"></a>The levelised cost of electricity provides the most intuitive metric for comparing generation costs across technologies and scenarios. Unlike total system cost or NPV, which are sensitive to demand projections and discount rates, LCOE expresses the average cost of producing one unit of electricity over the project lifetime, making it directly comparable to retail tariffs, benchmark studies, and international experience.</span>
<span id="cb1-201"><a href="#cb1-201" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-204"><a href="#cb1-204" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb1-205"><a href="#cb1-205" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-lcoe</span></span>
<span id="cb1-206"><a href="#cb1-206" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Levelised cost of electricity by scenario, with international benchmarks for context."</span></span>
<span id="cb1-207"><a href="#cb1-207" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-208"><a href="#cb1-208" aria-hidden="true" tabindex="-1"></a>lcoes <span class="op">=</span> {s: get_npv(s)[<span class="st">"lcoe"</span>] <span class="op">*</span> <span class="dv">100</span> <span class="cf">for</span> s <span class="kw">in</span> SCENARIO_IDS}</span>
<span id="cb1-209"><a href="#cb1-209" aria-hidden="true" tabindex="-1"></a>benchmarks <span class="op">=</span> cba.get(<span class="st">"benchmarks"</span>, {})</span>
<span id="cb1-210"><a href="#cb1-210" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-211"><a href="#cb1-211" aria-hidden="true" tabindex="-1"></a>fig <span class="op">=</span> go.Figure()</span>
<span id="cb1-212"><a href="#cb1-212" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-213"><a href="#cb1-213" aria-hidden="true" tabindex="-1"></a><span class="co"># Scenario bars</span></span>
<span id="cb1-214"><a href="#cb1-214" aria-hidden="true" tabindex="-1"></a>fig.add_trace(go.Bar(</span>
<span id="cb1-215"><a href="#cb1-215" aria-hidden="true" tabindex="-1"></a>    x<span class="op">=</span>[SCENARIO_SHORT[s] <span class="cf">for</span> s <span class="kw">in</span> SCENARIO_IDS],</span>
<span id="cb1-216"><a href="#cb1-216" aria-hidden="true" tabindex="-1"></a>    y<span class="op">=</span>[lcoes[s] <span class="cf">for</span> s <span class="kw">in</span> SCENARIO_IDS],</span>
<span id="cb1-217"><a href="#cb1-217" aria-hidden="true" tabindex="-1"></a>    marker_color<span class="op">=</span>[SCENARIO_COLORS[s] <span class="cf">for</span> s <span class="kw">in</span> SCENARIO_IDS],</span>
<span id="cb1-218"><a href="#cb1-218" aria-hidden="true" tabindex="-1"></a>    text<span class="op">=</span>[<span class="ss">f"</span><span class="sc">{</span>lcoes[s]<span class="sc">:.1f}</span><span class="ss">¢"</span> <span class="cf">for</span> s <span class="kw">in</span> SCENARIO_IDS],</span>
<span id="cb1-219"><a href="#cb1-219" aria-hidden="true" tabindex="-1"></a>    textposition<span class="op">=</span><span class="st">"outside"</span>,</span>
<span id="cb1-220"><a href="#cb1-220" aria-hidden="true" tabindex="-1"></a>    name<span class="op">=</span><span class="st">"Maldives Scenarios"</span>,</span>
<span id="cb1-221"><a href="#cb1-221" aria-hidden="true" tabindex="-1"></a>))</span>
<span id="cb1-222"><a href="#cb1-222" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-223"><a href="#cb1-223" aria-hidden="true" tabindex="-1"></a><span class="co"># Benchmark lines</span></span>
<span id="cb1-224"><a href="#cb1-224" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> benchmarks:</span>
<span id="cb1-225"><a href="#cb1-225" aria-hidden="true" tabindex="-1"></a>    bm_data <span class="op">=</span> [</span>
<span id="cb1-226"><a href="#cb1-226" aria-hidden="true" tabindex="-1"></a>        (<span class="st">"IRENA Global Solar"</span>, benchmarks.get(<span class="st">"global_solar_lcoe"</span>, <span class="fl">0.049</span>) <span class="op">*</span> <span class="dv">100</span>, <span class="st">"#27ae60"</span>),</span>
<span id="cb1-227"><a href="#cb1-227" aria-hidden="true" tabindex="-1"></a>        (<span class="st">"SIDS Average RE"</span>, benchmarks.get(<span class="st">"sids_avg_renewable_lcoe"</span>, <span class="fl">0.16</span>) <span class="op">*</span> <span class="dv">100</span>, <span class="st">"#f39c12"</span>),</span>
<span id="cb1-228"><a href="#cb1-228" aria-hidden="true" tabindex="-1"></a>        (<span class="st">"Global Diesel Mini-grid"</span>, benchmarks.get(<span class="st">"global_diesel_gen_lcoe"</span>, <span class="fl">0.28</span>) <span class="op">*</span> <span class="dv">100</span>, <span class="st">"#e74c3c"</span>),</span>
<span id="cb1-229"><a href="#cb1-229" aria-hidden="true" tabindex="-1"></a>    ]</span>
<span id="cb1-230"><a href="#cb1-230" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> label, val, color <span class="kw">in</span> bm_data:</span>
<span id="cb1-231"><a href="#cb1-231" aria-hidden="true" tabindex="-1"></a>        fig.add_hline(y<span class="op">=</span>val, line_dash<span class="op">=</span><span class="st">"dot"</span>, line_color<span class="op">=</span>color,</span>
<span id="cb1-232"><a href="#cb1-232" aria-hidden="true" tabindex="-1"></a>                      annotation_text<span class="op">=</span>label, annotation_position<span class="op">=</span><span class="st">"top left"</span>)</span>
<span id="cb1-233"><a href="#cb1-233" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-234"><a href="#cb1-234" aria-hidden="true" tabindex="-1"></a>fig.update_layout(</span>
<span id="cb1-235"><a href="#cb1-235" aria-hidden="true" tabindex="-1"></a>    title<span class="op">=</span><span class="st">"Levelised Cost of Electricity (¢/kWh)"</span>,</span>
<span id="cb1-236"><a href="#cb1-236" aria-hidden="true" tabindex="-1"></a>    yaxis_title<span class="op">=</span><span class="st">"LCOE (¢/kWh)"</span>,</span>
<span id="cb1-237"><a href="#cb1-237" aria-hidden="true" tabindex="-1"></a>    height<span class="op">=</span><span class="dv">450</span>,</span>
<span id="cb1-238"><a href="#cb1-238" aria-hidden="true" tabindex="-1"></a>    showlegend<span class="op">=</span><span class="va">False</span>,</span>
<span id="cb1-239"><a href="#cb1-239" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-240"><a href="#cb1-240" aria-hidden="true" tabindex="-1"></a>fig.show()</span>
<span id="cb1-241"><a href="#cb1-241" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-242"><a href="#cb1-242" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-243"><a href="#cb1-243" aria-hidden="true" tabindex="-1"></a>The LCOE comparison chart places the Maldives scenarios in the context of international benchmarks. The diesel BAU LCOE substantially exceeds global diesel mini-grid averages, reflecting the particular cost penalties of small-island generation: fuel transport surcharges, scale inefficiencies of small generators, and high labour costs for maintenance on remote islands. The renewable-based scenarios achieve LCOEs that approach the SIDS average for renewable generation and, in some cases, come close to global utility-scale solar benchmarks — a remarkable achievement for a small island nation with severe logistical constraints. The gap between the BAU LCOE and the best alternative LCOEs represents the per-unit cost advantage of transition, which compounds into the billions of dollars of NPV savings documented above.</span>
<span id="cb1-244"><a href="#cb1-244" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-245"><a href="#cb1-245" aria-hidden="true" tabindex="-1"></a><span class="fu">## Emissions Trajectories</span></span>
<span id="cb1-246"><a href="#cb1-246" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-247"><a href="#cb1-247" aria-hidden="true" tabindex="-1"></a>Climate impact is a critical dimension of the energy transition decision, both because the Maldives has committed to ambitious emissions reduction targets under the Paris Agreement and because, as the world's lowest-lying nation, it has an existential stake in global climate action. The figure below compares cumulative CO₂ emissions across all seven scenarios over the 30-year analysis period.</span>
<span id="cb1-248"><a href="#cb1-248" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-251"><a href="#cb1-251" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb1-252"><a href="#cb1-252" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-emissions</span></span>
<span id="cb1-253"><a href="#cb1-253" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Cumulative CO₂ emissions by scenario. All alternatives achieve significant emission reductions versus diesel BAU."</span></span>
<span id="cb1-254"><a href="#cb1-254" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-255"><a href="#cb1-255" aria-hidden="true" tabindex="-1"></a>emissions <span class="op">=</span> {s: summaries[s][<span class="st">"total_emissions_mtco2"</span>] <span class="cf">for</span> s <span class="kw">in</span> SCENARIO_IDS}</span>
<span id="cb1-256"><a href="#cb1-256" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-257"><a href="#cb1-257" aria-hidden="true" tabindex="-1"></a>fig <span class="op">=</span> bar_scenario_comparison(</span>
<span id="cb1-258"><a href="#cb1-258" aria-hidden="true" tabindex="-1"></a>    values<span class="op">=</span>emissions,</span>
<span id="cb1-259"><a href="#cb1-259" aria-hidden="true" tabindex="-1"></a>    title<span class="op">=</span><span class="st">"Cumulative CO₂ Emissions, 2026–2056 (MtCO₂)"</span>,</span>
<span id="cb1-260"><a href="#cb1-260" aria-hidden="true" tabindex="-1"></a>    yaxis_title<span class="op">=</span><span class="st">"MtCO₂"</span>,</span>
<span id="cb1-261"><a href="#cb1-261" aria-hidden="true" tabindex="-1"></a>    highlight_bau<span class="op">=</span><span class="va">True</span>,</span>
<span id="cb1-262"><a href="#cb1-262" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-263"><a href="#cb1-263" aria-hidden="true" tabindex="-1"></a>fig.show()</span>
<span id="cb1-264"><a href="#cb1-264" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-265"><a href="#cb1-265" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-268"><a href="#cb1-268" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb1-269"><a href="#cb1-269" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: emission-reductions</span></span>
<span id="cb1-270"><a href="#cb1-270" aria-hidden="true" tabindex="-1"></a>bau_em <span class="op">=</span> summaries[<span class="st">"bau"</span>][<span class="st">"total_emissions_mtco2"</span>]</span>
<span id="cb1-271"><a href="#cb1-271" aria-hidden="true" tabindex="-1"></a>best_em_sid <span class="op">=</span> <span class="bu">min</span>(ALT_SCENARIOS, key<span class="op">=</span><span class="kw">lambda</span> s: summaries[s][<span class="st">"total_emissions_mtco2"</span>])</span>
<span id="cb1-272"><a href="#cb1-272" aria-hidden="true" tabindex="-1"></a>best_em <span class="op">=</span> summaries[best_em_sid][<span class="st">"total_emissions_mtco2"</span>]</span>
<span id="cb1-273"><a href="#cb1-273" aria-hidden="true" tabindex="-1"></a>reduction_pct <span class="op">=</span> (<span class="dv">1</span> <span class="op">-</span> best_em <span class="op">/</span> bau_em) <span class="op">*</span> <span class="dv">100</span></span>
<span id="cb1-274"><a href="#cb1-274" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-275"><a href="#cb1-275" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-276"><a href="#cb1-276" aria-hidden="true" tabindex="-1"></a>The emissions comparison reveals the enormous environmental dividend of transition. Under diesel BAU, the Maldives electricity sector would emit <span class="in">`{python} f"{bau_em:,.1f}"`</span> million tonnes of CO₂ over the <span class="in">`{python} f"{cba['end_year'] - cba['base_year']}"`</span>-year period. The cleanest scenario, <span class="in">`{python} SCENARIO_SHORT[best_em_sid]`</span>, reduces cumulative emissions by <span class="in">`{python} f"{reduction_pct:.0f}"`</span> per cent to just <span class="in">`{python} f"{best_em:,.1f}"`</span> million tonnes. Even the scenarios that retain some fossil fuel component — such as the LNG Transition (S7), which achieves a <span class="in">`{python} f"{(1 - param('LNG Emission Factor') / 0.72)*100:.0f}"`</span> per cent reduction in emission intensity by switching from diesel to natural gas — deliver substantial climate benefits relative to the status quo.</span>
<span id="cb1-277"><a href="#cb1-277" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-278"><a href="#cb1-278" aria-hidden="true" tabindex="-1"></a>The emissions ranking does not perfectly mirror the economic ranking, which creates an interesting policy tension. Some scenarios that are slightly less cost-optimal deliver substantially deeper decarbonisation, meaning that policymakers face a genuine choice about how much additional cost (if any) they are willing to accept to achieve greater emissions reduction. However, the trade-off is modest: the cost difference between the most economically efficient scenario and the most environmentally ambitious one is small relative to the savings both deliver versus diesel.</span>
<span id="cb1-279"><a href="#cb1-279" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-280"><a href="#cb1-280" aria-hidden="true" tabindex="-1"></a><span class="fu">## The India Cable vs. Domestic Alternatives</span></span>
<span id="cb1-281"><a href="#cb1-281" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-282"><a href="#cb1-282" aria-hidden="true" tabindex="-1"></a>A question of particular strategic importance is whether the India submarine cable (S2) justifies its substantial cost premium over domestic renewable alternatives. While the cable clearly dominates diesel BAU (as do all alternatives), the relevant policy comparison is against the next-best option that does not require international infrastructure. The incremental analysis comparing S2 (Full Integration) against S3 (National Grid, the best domestic alternative) directly addresses this question.</span>
<span id="cb1-283"><a href="#cb1-283" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-286"><a href="#cb1-286" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb1-287"><a href="#cb1-287" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fi-vs-ng</span></span>
<span id="cb1-288"><a href="#cb1-288" aria-hidden="true" tabindex="-1"></a>fi_vs_ng <span class="op">=</span> cba[<span class="st">"incremental_fi_vs_ng"</span>]</span>
<span id="cb1-289"><a href="#cb1-289" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-290"><a href="#cb1-290" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-291"><a href="#cb1-291" aria-hidden="true" tabindex="-1"></a>The incremental analysis reveals that the India cable requires <span class="in">`{python} fmt_usd(fi_vs_ng['additional_capex'])`</span> in additional capital expenditure beyond what the National Grid domestic scenario would cost. This additional investment yields an incremental benefit-cost ratio of only <span class="in">`{python} f"{fi_vs_ng['bcr']:.2f}"`</span>, which falls below the 1.0 threshold — meaning that the marginal costs of the cable exceed its marginal benefits relative to domestic solar-plus-battery. The incremental IRR of <span class="in">`{python} f"{fi_vs_ng['irr']*100:.1f}"`</span> per cent is below the <span class="in">`{python} f"{cba['discount_rate']*100:.0f}"`</span> per cent social discount rate, and the incremental payback period extends to <span class="in">`{python} fi_vs_ng['payback_years']`</span> years, raising questions about the cable's economic justification on the margin.</span>
<span id="cb1-292"><a href="#cb1-292" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-293"><a href="#cb1-293" aria-hidden="true" tabindex="-1"></a>::: {.callout-important}</span>
<span id="cb1-294"><a href="#cb1-294" aria-hidden="true" tabindex="-1"></a><span class="fu">## The cable does not pay for itself on the margin</span></span>
<span id="cb1-295"><a href="#cb1-295" aria-hidden="true" tabindex="-1"></a>While S2 saves money versus *diesel* (BCR `{python} f"{get_incremental('full_integration')['bcr']:.1f}"` ×), it does *not* save money versus *domestic solar+battery* (S3). The cable's marginal BCR of `{python} f"{fi_vs_ng['bcr']:.2f}"` means that every additional dollar invested in the cable yields only `{python} f"{fi_vs_ng['bcr']*100:.0f}"` cents of additional benefit. Domestic RE is more cost-effective.</span>
<span id="cb1-296"><a href="#cb1-296" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-297"><a href="#cb1-297" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-298"><a href="#cb1-298" aria-hidden="true" tabindex="-1"></a>This finding does not categorically rule out the India cable — there may be strategic, geopolitical, or energy security arguments that fall outside the scope of economic CBA. However, it does establish that from a pure cost-effectiveness standpoint, the Maldives would be better served by investing the same capital in domestic solar, battery, and near-shore solar capacity. The cable's marginal economics would improve if India were to share the construction cost (the sensitivity analysis explores a 50 per cent cost-sharing scenario), if Indian electricity export prices were lower than assumed, or if domestic solar deployment encountered unforeseen cost escalation. These conditions are possible but uncertain, which reinforces the real-options argument for deferring the cable decision presented in @sec-real-options.</span>
</code><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->




</body></html>